wailsapp/wails

cmd/templates.go, cmd/templates/basic/go.mod.template, cmd/templates/basic/main.go.template, cmd/templates/custom/go.mod.template, cmd/templates/custom/main.go.template, cmd/templates/vuewebpack/frontend/package.json.template, cmd/templates/vuewebpack/go.mod.template, cmd/templates/vuewebpack/main.go.template, cmd/wails/3_build.go
=> Initial Port

cmd/bundle.go, cmd/wails/0_setup.go, cmd/wails/3_build.go
=> fixes building on linux

cmd/frameworks/main.go, cmd/wails/3_build.go
=> Fix frameworkspinner

binding_function.go, cmd/templates/vuewebpack/main.go.template
Made arg marshalling messages Debug rather than Info
=> Update vue template to use BoxString

assets/headless/index.html, renderer_headless.go
made reconnect modal a bit better
=> fix for ipc binding

cmd/wails/9_issue.go
=> fix: align with new bug template

CONTRIBUTORS.md, app.go, renderer.go, renderer_headless.go, renderer_webview.go
Removes very old backend methods now handled better in the frontend.
=> 112 deprecate backend injection of css js

cmd/linux.go, cmd/prerequisites.go, cmd/system.go
Hi all, new to wails and found that it didn't have support for Gentoo! Tested and working.
=> Add support for Gentoo

cmd/templates/create-react-app/frontend/package.json.template, cmd/templates/create-react-app/frontend/src/index.js
=> 145 fix react error windows

README.md, cmd/linux.go, cmd/prerequisites.go, cmd/system.go
#179 
+ fixed gentoo and archlinux support
+ README is uptodate! 
please note I completely removed `redhat` and `pop` until I fully test them :+1:
=> 179 parrot distributionsupport

lib/renderer/webview.go
=> fix: undefined: webview during build

cmd/wails/main.go
=> cmd/wails: report error status code to OS

CONTRIBUTORS.md, cmd/packages/windows/wails.rc, lib/renderer/webview/webview.h
Should fix the request at issue #352
=> Fix window icon on Windows

lib/interfaces/renderer.go, lib/renderer/bridge/bridge.go, lib/renderer/webview.go, lib/renderer/webview/webview.h, runtime/dialog.go
Reference #436 @leaanthony This is the remaining stuff related to #438 , support for OSX / Windows
=> 436 file dialog filter for win32 and cocoa

cmd/helpers.go
Leave windows files after building rather than tidy them up.
=> Don't clean up windows files

runtime/store.go
This changes the API for Subscribe() from:
```go
Subscribe( func(interface{}) )
```
to
```go
Subscribe( interface{} )
```
This is to allow developers to provide functions with store specific data types.
So instead of:
```go
store.Subscribe( func(d interface{}) {
realValue := d.(int) // Let's hope this works
})
```
You can now do:
```go
store.Subscribe( func(realValue int) {
// This always works
})
```
Failure to provide a function with the correct signature will throw a fatal error at runtime. Generics will provide us compile time errors....
=> Simplify Subscribe()

cmd/templates/angular-template/frontend/src/app/app-routing.module.ts
=> Revert "resolve angular routing broken when app is built"

cmd/helpers.go
=> Remove incorrect build flag

cmd/helpers.go, cmd/wails/4_build.go, cmd/wails/6_serve.go
Add additional information for Windows build / serve.
=> Add warnings for windows builds

cmd/helpers.go, cmd/project.go
Added field tags for forwarding at the build stageю
=> feat: tags build stage

v2/cmd/wails/internal/commands/build/build.go, v2/internal/ffenestri/contextmenus_darwin.c, v2/internal/ffenestri/ffenestri_darwin.c, v2/internal/ffenestri/ffenestri_darwin.h, v2/internal/ffenestri/menu_darwin.c, v2/internal/ffenestri/traymenu_darwin.c, v2/internal/ffenestri/traymenu_darwin.h, v2/pkg/commands/build/base.go, v2/pkg/commands/build/build.go, v2/pkg/commands/build/builder.go, v2/pkg/commands/build/desktop.go, v2/pkg/commands/build/server.go
* "darwin/arm64" and "darwin/universal" targets
* Verbose mode
=> V2 alpha arm

cmd/helpers.go, cmd/system.go
=> feat(cli): use gitconfig name as name prompt default value

cmd/templates/angular-template/frontend/package.json.template, cmd/templates/angular-template/template.json, cmd/templates/create-react-app/frontend/package.json.template, cmd/templates/create-react-app/template.json, cmd/templates/svelte/frontend/package.json.template, cmd/templates/svelte/template.json
Fixes #587 
Still need to test but don't see why this wouldn't work
=> fix(cli): use npm run serve as serve command in all templates

runtime/js/package-lock.json
=> Revert "Bump y18n from 4.0.0 to 4.0.1 in /runtime/js"

lib/renderer/webview/webview.h
=> Disable full screen button

lib/renderer/webview/webview.h
=> Revert "Disable full screen button"

v2/internal/bridge/client.go, v2/internal/runtime/js/runtime/bridge.js, v2/internal/runtime/js/runtime/package.json, v2/internal/runtime/js/runtime/src/package-lock.json, v2/internal/runtime/js/runtime/src/websocket.js
This PR implements the client to server notify functionality in V2. It consists of an update to the server to send the message, and and update to the javascript runtime. I've done a minor version bump on the runtime library.
=> [v2] Implement server to client notify support.

README.md, README.zh-Hans.md
- format file
- synchronize Chinese readme
- use a more standard language identifier
(#748)
=> Synchronize chinese readme

cmd/linux.go, cmd/linuxdb.yaml, cmd/system.go
=> Add NixOS support

v2/internal/frontend/desktop/windows/frontend.go
add ctral+A,arrowUp,left,down,right and del
=> Add commonly used shortcut keys

v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/app.tmpl.go, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/frontend/src/index.html, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/frontend/src/main.css, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/frontend/src/main.js, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/main.tmpl.go
Optimize the style of the default template vanilla, and add keyboard response.
=> feat(template): optimization template

v2/internal/ffenestri/windows/wv2runtime/browser.go
Fixed minimum version variable.
See https://github.com/wailsapp/wails/discussions/828#discussioncomment-1392221
=> Fix browser.go - minimum version

v2/cmd/wails/internal/commands/dev/dev.go
I wanted to learn more about how `wails dev` worked, but the action was quite a big piece of code to wrap my head around, so the easiest thing to do was to refactor. In theory, this should make the command a little more readable, and hopefully easier to work on. I focused mainly on splitting up the main command action into functions of smaller related chunks. I also took the liberty to clean up a little while I was at it. There's a lot more that could be done, but I figured this was a good place to stop. Feel free to tell me if it's terrible 😅 
- added `devFlags` data structure for managing flags
- created `defaultDevFlags()` for generating default `devFlags` struct
- created `loadAndMergeProjectConfig()` to consolidate wails.json interaction
- re-arranged some variable creation and logic …
=> Refactored `wails dev` command:

README.md, README.zh-Hans.md, website/docs/credits.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/credits.mdx
LetheanMovement is our community group, both us :)
=> Update Lethean project url

v2/internal/frontend/desktop/darwin/WailsContext.m
=> [macOS] Fix background color

v2/pkg/commands/build/base.go
=> [v2] Add windowsgui ldflag when crosscompiling for windows

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/window.go
Fix #969 depends on leaanthony/winc#3
=> [v2] Use invoke to dispatch callbacks on windows

v2/internal/frontend/desktop/windows/frontend.go
=> [v2] windows: Do not apply WindowStartState on reloads

v2/cmd/wails/internal/commands/generate/template/base/package.json, v2/cmd/wails/internal/commands/generate/template/template.go
Adding name and author, also found out while trying to find options for value escaping the string conversion isnt needed :)
=> Adding name and author, + json handling improvement

v2/cmd/wails/internal/commands/build/build.go, v2/go.mod, v2/go.sum, v2/pkg/commands/build/packager.go
=> [v2] windows: Add arm64 support

v2/pkg/buildassets/build/windows/info.tmpl.json, v2/pkg/commands/build/desktop_darwin.go, v2/pkg/commands/build/packager.go
=> [v2] Windows: Add file information for windows

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/window.go
Fix #986 depends on leaanthony/winc#4
=> [v2] Do not block during processing of messages

v2/internal/frontend/desktop/windows/window.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/options.mdx
=> [windows] Support drawing a frame for frameless to support hiding the titlebar

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/windows/frontend.go
Fix #993 depends on leaanthony/go-webview2#4
=> [v2] Fix memory leak in processRequest for windows and darwin

v2/internal/frontend/desktop/common/uri_translate.go, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go
=> [v2] Improve translation of URI to file to be loaded

website/docs/community/links.mdx, website/docs/reference/options.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/links.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/showcase/ytd.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/bleeding-edge.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/routing.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/howdoesitwork.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/options.mdx
- synchronize chinese documents
- optimize english documents
=> docs: synchronize and optimize documents

v2/cmd/wails/internal/commands/build/build.go, v2/pkg/commands/build/base.go, v2/pkg/commands/build/build.go
**Add option:**
-m Skip mod tidy before compile
Resolves issue #1020
=> [v2] feature / Add flag to skip mod tidy

website/docs/community/showcase/riftshare.mdx
Hey, I created an app for file sharing based on wails. Would love to have it on your showcase.
=> Add Riftshare to community showcase

cmd/fs.go, cmd/linuxdb.go
=> Make linuxdb.yaml an embedded resource

cmd/linux.go, cmd/linuxdb.yaml, cmd/system.go
=> add uos linux distro

website/docs/community/templates.mdx
Add templates for using Svelte with Vite and optionally TailwindCSS v3
=> Add templates for using Svelte with Vite

v2/internal/frontend/desktop/linux/window.go
Uses `g_idle_add` to execute the Javascript on the main thread when it is idle.
Works fine on both my amd64 and arm64 linux machines.
=> [linux] execute JS on main thread

v2/internal/frontend/desktop/windows/window.go
The following features are now supported for framless windows
- Allow aero snap
- Minimize and maximize animations
- Allow minimizing/restoring by clicking onto the taskbar icon
- If EnableFramelessBorder is used, the default application border with glass effect is used
Change: Menu is not supported anymore if the window is frameless.
Fix #1084
=> [v2] windows: Improve frameless window handling

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/frontend.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx
=> [v2, windows] Add WebviewUserDataPath to windows options

.github/workflows/deploy-website-to-wails.top-mirror.yml
Added site auto-sync script(8:00 and 20:00 every day) to keep mirror sites in sync with the official site at all times.
=> chore(action): add auto sync script

v2/go.mod, v2/go.sum
Contains fixes for #1094 and resize constraining
Fix #1094
=> [v2, windows] Bump winc

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/window.go
This adjusts the window size if the window is moved from one
monitor to another with a different DPI scaling
=> [v2, windows] Apply suggested window size during DPI changed event

v2/pkg/commands/build/packager.go
=> Update icon.ico file mode

v2/internal/frontend/desktop/windows/window.go
=> [v2, windows] Do not show caption buttons if frameless and translucent+transparency

v2/internal/system/system_linux.go
Looks for non-PM installed versions of npm, docker and upx
=> [linux] Fix discovery of npm, docker and upx

v2/internal/frontend/desktop/common/process_request.go, v2/internal/frontend/desktop/common/uri_translate.go, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go
=> [v2] Consolidate processRequest, improve logging and error handling

v2/cmd/wails/internal/commands/dev/dev.go
=> Run watcher after initial build

v2/internal/frontend/desktop/linux/frontend.go
=> ensure binary resources can be served

v2/internal/frontend/assetserver/assetserver_desktop.go, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go
=> Only retry loading assets when loading from disk

v2/internal/frontend/desktop/windows/frontend.go
=> [v2, windows] Fix maximised start state

v2/internal/frontend/desktop/darwin/Application.m
=> Fix memory leak in ExecJS for Mac

v2/cmd/wails/internal/commands/build/build.go, v2/pkg/commands/build/packager.go
need to depend on https://github.com/leaanthony/go-webview2/pull/8#issue-1164702663
=> Build added win32 compatibility

v2/cmd/wails/internal/commands/dev/dev.go
My first ever open source contribution. I hope I did it correctly ;-) There may be a more elegant solution but this is what ended up working under most circumstances ( that I was able to try out )
=> Fix, or at least a workaround, for (#1232)

website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/gettingstarted/firstproject.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/manual-builds.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/troubleshooting.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/options.mdx
Sync recently added documents.
=> docs: sync documents

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/frontend.go
Fixes #1254 
Tested focusing input, alt-tab, alt-tab = focus back
Also tested focus event in JS.
=> Ensure Focus is regained by Webview2 when tabbing

v2/internal/frontend/desktop/darwin/Application.m
=> Better close for Mac

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/menu.go, v2/internal/frontend/desktop/windows/theme.go, v2/internal/frontend/desktop/windows/win32/consts.go, v2/internal/frontend/desktop/windows/win32/theme.go, v2/internal/frontend/desktop/windows/win32/window.go, v2/internal/frontend/desktop/windows/window.go, v2/internal/system/operatingsystem/os_windows.go, v2/internal/system/operatingsystem/version_windows.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx
This is an experimental PR for supporting Dark mode in Windows. Potential fix for #1149
=> [Feature/1149] Dark mode

v2/internal/frontend/desktop/linux/window.go
=> prevent close event being propagated when handled in app

v2/go.mod, v2/go.sum
=> remove duplicate mimetype entries

v2/internal/frontend/runtime/wrapper/events.js, v2/internal/frontend/runtime/wrapper/runtime.d.ts
I found when trying to use the documented method `EventsOff` that I was having an error due that is not declare. I have tested adding it here and works for me. Since the file does not contains the header saying is generated I think is ok. But if it is not please let me know how is the correct way to handle it.
Thanks.
=> Add missing method declaration

website/versioned_docs/version-v2.0.0-beta.34/community/templates.mdx
a template with Vite + React + TypeScript
=> add a template with Vite + React + TypeScript

website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/templates.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.0.0-beta.34/community/templates.mdx
add a template with Vite + React + TypeScript
基于 Vite + React + TypeScript 的模板
=> add a template docs : zh-Hans

v2/internal/binding/generate.go
Fixes #1355 
@ianmjones - a quick fix, quickly tested 👍
=> Fix for TS/JS generation on methods with no returns

v2/cmd/wails/internal/commands/initialise/templates/generate/assets/common/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/lit-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/lit/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/preact-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/preact/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/react-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/react/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/svelte-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/svelte/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/vue-ts/frontend/wailsjs/runtime/runtime.js, v2/cmd/wails/internal/commands/initialise/templates/templates/vue/frontend/wailsjs/runtime/runtime.js
=> [v2] Events | fixes #1388

v2/internal/frontend/assetserver/assethandler.go, v2/internal/frontend/assetserver/assetserver.go, v2/internal/frontend/devserver/devserver.go
=> bugfix: correct typo

website/docs/reference/project-config.mdx
=> Fix typo in docs

website/docs/community/templates.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/templates.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.0.0-beta.34/community/templates.mdx
Add [Next.js](https://github.com/vercel/next.js) template.
=> Add Next.js template

website/docs/guides/frontend.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/guides/frontend.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.0.0-beta.34/guides/frontend.mdx, website/versioned_docs/version-v2.0.0-beta.34/guides/frontend.mdx, website/versioned_docs/version-v2.0.0-beta.35/guides/frontend.mdx
Correct typos in all versions of the document and resend the PR.😀
=> fix typo bindings.js to ipc.js

website/docs/reference/runtime/intro.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/runtime/intro.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.0.0-beta.34/reference/runtime/intro.mdx, website/versioned_docs/version-v2.0.0-beta.35/reference/runtime/intro.mdx, website/versioned_docs/version-v2.0.0-beta.37/reference/runtime/intro.mdx
Corrected these in all versions of the document 😄
=> Fix small typo in docs

website/docs/community/showcase/surge.mdx
fix the url to surge in the docs
=> fix the url to surge

v2/internal/frontend/assetserver/assethandler.go
=> [v2] AssetsHandler remove retry logic in dev mode

website/versioned_docs/version-v2.0.0-beta.37/community/templates.mdx
I read this issue #1491 and decided to create a Solid JS template for Wails.
=> Add Solid JS template

v2/internal/binding/generate.go, v2/internal/binding/generate_test.go
=> Support Maps in TS conversion

v2/internal/system/packagemanager/apt.go
=> Fix checking for installed apt package in none English session.

v2/cmd/wails/internal/commands/dev/stdout_scanner.go
=> Check for line length when scanning for local devserver url

website/versioned_docs/version-v2.0.0-beta.38/guides/troubleshooting.mdx
Issues with Vite's optimizer
https://github.com/wailsapp/wails/issues/1582
=> Add troubleshooting for `Not Found` error

website/versioned_docs/version-v2.0.0-beta.39/reference/menus.mdx
Reference https://github.com/wailsapp/wails/issues/1588
=> Update example for macOS Menu

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/project/project.go
=> Install dev dependencies before starting dev mode

website/versioned_docs/version-v2.0.0-beta.39/reference/options.mdx
Add comments and notes to recommend WindowStartState: options.Fullscreen instead
=> Deprecate Fullscreen appoption

website/docs/community/templates.mdx
Add [wails-sveltekit-template](https://github.com/h8gi/wails-sveltekit-template) to Community / Templates page.
=> add wails-sveltekit-template

v2/internal/frontend/desktop/linux/window.go
=> Move SetMin/Max calls to main thread

v2/cmd/wails/internal/commands/dev/dev.go, v2/pkg/commands/build/build.go
Breaking Change: Ignore flags take precedence over Force flag.
Potential fix for #1680
=> [v2, dev] Build frontend only before starting the dev watcher command

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/project/project.go
=> [v2, dev] Improve error message for auto dev server discovery without a dev watcher

v2/cmd/wails/internal/commands/build/build.go
=> [v2, build] Bug fix collecting of output binaries for platforms

website/docs/tutorials/helloworld.mdx
I deleted some text that was written outside the img tag
=> Text outside style's brackets

README.ja.md, README.md
Hello!
I have recently discovered and touched Wails. And I am experiencing that Wails are very cool!
I created a Japanese version of the README to let people in also Japanese know more about it.
P.S.
I am creating this PR while listening to Resistance Is Futile by Manic Street Preachers as described in the README.
This music is also very good.
=> Add README.ja.md

website/docs/guides/vscode.mdx
Change frontend/tsconfig.js to frontend/tsconfig.json in vscode guide page.
=> fix frontend/tsconfig.js

v2/internal/binding/generate.go
=> Use Promise<void> when Go routine does not output

.github/workflows/check_docs.yml, .github/workflows/pr.yml
Adds a workflow for running `go test` on PRs
=> Add PR checks

.github/workflows/projects.yml
Updates labels based on which project column a card is in
=> Auto label project cards

.github/workflows/issue-translator.yml
Detects if issues/comments are non-english and provides a translation if so
=> Add issue translator

website/versioned_docs/version-v2.0.0/guides/obfuscated.mdx
the option in the docs is the wrong flag you have to add a d at the end
=> obfuscated instead of obfuscate in the docs

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/app/app_dev.go
=> [dev] Do not generate bindings in the dev app itself

v2/cmd/wails/internal/commands/initialise/initialise.go
fixed: https://github.com/wailsapp/wails/issues/1928
=> fix: remove the `.git` directory in the template

website/docs/community/templates.mdx
Add a new community template for React+TS+Vite+Tailwind
=> add react-ts-vite-tailwind template

v2/internal/frontend/devserver/devserver.go
Fixes https://github.com/wailsapp/wails/issues/1919
I made the minimum necessary changes to get the dev server working again.
I understand there was a recent refactor in #1909, so please let me know if these changes get in the way of something else.
=> Fix wails dev

v2/internal/app/app_dev.go
=> [dev] Do not try to infer assetdir from fs.FS when a frontend dev server is in use

v2/internal/frontend/desktop/darwin/inspector.go
=> [darwin, inspector] Fix build

v2/internal/system/system_darwin.go, website/src/pages/changelog.mdx
Sample output
```sh
Dependency			Package Name	Status		Version
----------			------------	------		-------
Xcode command line tools  	N/A 		Installed 	2396
npm  				N/A 		Installed 	8.19.2
*Xcode 				N/A 		Installed 	14.1 (14B47b)
*upx  				N/A 		Available
*nsis  				N/A 		Installed 	v3.08
```
=> [darwin] Show Xcode version in wails doctor

website/versioned_docs/version-v2.2.0/guides/obfuscated.mdx
=> Update obfuscated.mdx to fix a typo

v2/cmd/wails/internal/commands/dev/dev_windows.go
Fixed: https://github.com/wailsapp/wails/issues/2145
=> fix(cli): fix windows platform install error

website/docs/guides/mac-appstore.mdx
Fixes #2028 
I haven't done the process from scratch in several months so this is what I can remember. Happy to make revisions as people provide feedback.
=> Initial Mac App Store Guide

website/versioned_docs/version-v2.2.0/community/templates.mdx
vite + solid + js 
vite + solid + ts
=> Added  templates

scripts/sponsors/generate-sponsor-image.sh, scripts/sponsors/package-lock.json, scripts/sponsors/package.json
=> chore: fix-generate-sponsor

v2/internal/shell/env.go, v2/internal/shell/env_test.go, v2/internal/shell/shell.go, v2/pkg/commands/bindings/bindings.go, v2/pkg/commands/build/base.go, v2/pkg/commands/build/base_test.go
Otherwise this will clash if an app also uses flags internally
=> [bindings] Pass ts_generation flags as env variable

v2/internal/frontend/assetserver/assethandler.go
I've split out these checks from PR #2203 because that PR might take longer until it has been fully discussed. But still it would be good to have these checks integrated before the next release. Especially because this is a follow-up for PR #2110 which is not yet released.
=> [assetHandler] Add request path checks

website/docusaurus.config.js, website/src/pages/community-guide.mdx
Begin changing pointers from Slack to Discord 👀
=> Website / Documentation - Slack to Discord

v2/internal/platform/win32/consts.go
=> [windows] Fix compile error for 386 platform

v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/create_env_native.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/native_module.go
=> [windows] Add support for AdditionalBrowserArgs to the legacy Webview2Loader

README.ja.md, README.ko.md, README.md, README.zh-Hans.md
Related issue : https://github.com/badges/shields/issues/8671
Before :
After :
=> Fix Broken Badge

website/docs/community/showcase/bulletinboard.mdx
Fixing the title to properly reflect the page. Somehow I messed up the merge.
=> The title was still wrong

v2/pkg/buildassets/build/windows/installer/project.nsi, v2/pkg/buildassets/build/windows/installer/wails_tools.nsh, website/src/pages/changelog.mdx
=> [nsis] Adjust template to install shortcuts for all users

v3/internal/parser/README.md, v3/internal/parser/parser.go, v3/internal/parser/parser_test.go, v3/internal/parser/testdata/variable_single_from_function/main.go, v3/internal/parser/testdata/variable_single_from_other_function/main.go, v3/internal/parser/testdata/variable_single_from_other_function/services/other.go
Two new test cases:
1. assignment from function call in same package
2. assignment from function call in different package
Also updating readme and adding TODO stub for new code.
=> v3 parser: add some more test cases (functions)

v2/internal/frontend/runtime/events.go, website/src/pages/changelog.mdx
=> [events] Fix race condition and missing unlock of mutex

scripts/sync-translated-documents.sh
Update sync translated document script
=> feat: update sync translated document script

v2/internal/frontend/devserver/devserver.go, website/src/pages/changelog.mdx
=> [dev] Fix panic in devserver when using the logger

website/docs/reference/project-config.mdx
Optimize code block display style, easy to display and translate.
=> docs: optimize code block display style

website/src/pages/changelog.mdx
Please let me know if the dates for other languages need to be made.
Keep up the good work 👍🏻 🚀
=> Fix dates in changelog

.github/workflows/push.yml
This appears to be a mistake on my part, and it causes invalid uploads to be performed at some point. 😭
=> chore: fix push.yml

v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/webkit2.go, v2/pkg/assetserver/webview/request_linux.go, v2/pkg/assetserver/webview/responsewriter.go, v2/pkg/assetserver/webview/responsewriter_darwin.go, v2/pkg/assetserver/webview/responsewriter_linux.go, v2/pkg/assetserver/webview/webkit2_36.go, v2/pkg/assetserver/webview/webkit2_legacy.go
This PR brings the Linux AssetServer support to the v3 branch.
=> [assetserver] Add linux platform implementation

website/docs/guides/routing.mdx
Supplementary submission: https://github.com/wailsapp/wails/pull/2544
=> docs: update routing.mdx

website/docs/reference/menus.mdx
=> annotated menu example and updated runtime.Quit call

.github/workflows/generate-contributors.yml, .github/workflows/label-sponsors.yml, .github/workflows/push.yml, .github/workflows/sync-translated-documents.yml, Taskfile.yaml
=> chore: update auto workflows

website/Taskfile.yml
=> chore: fix pnpm environment settings

v2/cmd/wails/flags/dev.go, v2/cmd/wails/internal/dev/dev.go, website/src/pages/changelog.mdx
=> [v2, dev] Fix skipbindings flag in wails dev

v3/pkg/application/screen_darwin.go
Adding in the missing impl methods for Darwin
=> [darwin] add getPrimaryScreen/getScreens to impl

v2/internal/frontend/desktop/linux/window.go, website/i18n/zh-Hans/docusaurus-plugin-content-pages/changelog.mdx, website/src/pages/changelog.mdx
Fixes #2605, tested successfully on Manjaro with Gnome 43.3 installed.
=> [v2, linux] Fix StartHidden option not working on Linux

.github/ISSUE_TEMPLATE/config.yml, README.ja.md, README.ko.md, README.md, README.zh-Hans.md
*If you don't find it troublesome, you can add `chat.wails.io` domain name resolution, just like `translate.wails.io`.*
=> chore: update channel

.github/workflows/sync-translated-documents.yml, v2/tools/release/release.go, website/src/pages/changelog.mdx
=> docs: improve documentation

v2/cmd/wails/doctor.go, website/src/pages/changelog.mdx
Hi, I restyled the `doctor` command a little to make it more appealing. I kept all original details, just added some eye-candy.
Let me know what you think 😄 
---
I didn't make a ticket for this, as it's just a little refactor.
=> Change style of doctor command

v3/Taskfile.yaml, v3/internal/runtime/.gitignore, v3/internal/runtime/Taskfile.yaml
=> chore: split Taskfile

website/Taskfile.yml, website/crowdin.yml, website/package.json, website/src/api/crowdin.js
Put the `v2` document into the v2 branch of Crowdin, and update the translation progress of each language of the previously obtained project to the translation progress of each language of the corresponding branch of the obtained project.(This is also to ensure that adding v3 documents to Crowdin will not affect the translation progress data of v2 documents.)
=> feat(website): update the `Crowdin` branch

v2/pkg/assetserver/assethandler_external.go, v2/pkg/assetserver/assetserver_webview.go, website/src/pages/changelog.mdx
=> [assetServer] Make WebView request URL and RequestURI RFC and Go docs compliant

website/docs/community/templates.mdx
I added a template with Vite, React, TailwindCSS, TypeScript, and shadcn/ui.
=> Added shadcn-ui template

v3/examples/contextmenus/assets/index.html, v3/examples/drag-n-drop/assets/index.html, v3/examples/events/assets/index.html, v3/examples/plain/main.go, v3/examples/wml/assets/index.html
Some examples had a white background behind a white text on windows.
=> [v3] Fix examples background color

README.zh-Hans.md
Fixed a link error
Wrong link of  README.zh-Hans.md
=> Docs: Wrong link of  README.zh-Hans.md

README.es.md, README.ja.md, README.ko.md, README.md, README.zh-Hans.md
This change introduces readme.es.md which translates the original README.md into the spanish language.
Fixes #2810 
=> Docs: add spanish readme translation

v3/internal/assetserver/webview/responsewriter_linux.go, v3/internal/assetserver/webview/responsewriter_linux_purego.go, v3/pkg/application/application_linux.go, v3/pkg/application/systemtray_linux.go, v3/pkg/application/webview_window_linux.go
Updates to match the most recent changes for Linux.
Still not 100% working BUT it compiles.
=> V3 alpha linux

website/src/pages/changelog.mdx, website/versioned_docs/version-v2.5.0/community/templates.mdx
=> add wails-sveltekit-ts

website/docs/community/templates.mdx, website/src/pages/changelog.mdx
Added an updated svelte community template
=> Add updated svelte template 

README.es.md, README.ja.md, README.ko.md, README.md, README.pt-br.md, README.zh-Hans.md
Addition of readme file in Brazilian Portuguese language.
=> feat: add readme pt-br

v3/pkg/w32/image.go, v3/pkg/w32/popupmenu.go
=> [v3] completing missing build tags

website/src/pages/changelog.mdx, website/versioned_docs/version-v2.6.0/reference/options.mdx
=> Fix typo on https://wails.io/docs/reference/options#application-options

v3/pkg/application/webview_window.go
=> [v3] Update webview_window.go

website/versioned_docs/version-v2.6.0/community/templates.mdx
=> Add minimal React template

v2/internal/frontend/desktop/darwin/AppDelegate.m, v2/internal/frontend/desktop/darwin/WailsContext.m, website/src/pages/changelog.mdx
=> [v2/Mac] Change Window Level

website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community/templates.mdx
I developed a software that is designed for wails window Hope can start the project Added to the document template GoEasyDesigner is free open source project in address to https://github.com/duolabmeng6/GoEasyDesigner
=> I developed a window designer software that I hope can be added to template

mkdocs-website/shared/status.csv, website/src/pages/changelog.mdx
According to my testing for windows drag and drop, this flag should be enabled.
=> update windows drag and drop to working

website/docs/guides/signing.mdx
On November 1st 2023, Apple's notarization service [stopped accepting requests](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) using the `altool` binary, which [Gon](https://github.com/mitchellh/gon) uses under the hood.
In response to this, Mitchell Hashimoto decided to archive Gon (as he doesn't use it hugely himself) and encouraged the community to fork it.
There had been a few forks floating around but one that I settled on myself is from [Bearer](https://github.com/Bearer/gon), a company I know nothing about but seemed to have the most work done on its fork from a brief glance around.
It's also what I'm personally using for [October](https://github.com/marcus-crane/october) at the moment although it's really a pretty boring tool that …
=> (docs): Update code signing page to use a fork of Gon that supports new macOS signing flows

mkdocs-website/shared/alpha2.csv
=> Update WSL alpha2 support

mkdocs-website/docs/en/changelog.md, v2/internal/frontend/desktop/darwin/WailsMenu.m, v3/pkg/application/menuitem_darwin.go
=> Fix hex keys5

mkdocs-website/docs/en/changelog.md, v3/pkg/application/webview_window_windows.go
Before: 
After:
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Windows
=> [v3/windows] Fix dpi scaling on start up

mkdocs-website/docs/en/changelog.md, v3/pkg/application/application.go
=> [v3] export `SetIcon` method

mkdocs-website/docs/en/changelog.md, v3/pkg/application/application.go, v3/pkg/application/options_application.go
Move`OnShutdown` to `application.Options`.
=> [v3] Improve OnShutdown

mkdocs-website/docs/en/changelog.md, v3/internal/assetserver/assetserver.go
I'm create window with 
```go
window := application.Get().NewWebviewWindowWithOptions(application.WebviewWindowOptions{
Title:          "Software update",
Name:           "update",
URL:            "/software-update/index/",
})
```
When it created twice, the URL of the window is `/software-update/index/software-update/index/`
=> v3: fix wrong baseURL when open window twice

website/versioned_docs/version-v2.8.0/community/templates.mdx
Add a new template: wails-next-tailwind-shadcnui-ts
Changes#
=> Add a new template: wails-next-tailwind-shadcnui-ts

v2/internal/binding/reflect.go, v2/internal/frontend/desktop/windows/winc/app.go, v2/pkg/assetserver/assethandler.go, v2/pkg/assetserver/assetserver_webview.go, v2/pkg/mac/notification_darwin.go, v2/pkg/runtime/screen.go
=> chore: fix function names in comment

v3/go.mod, v3/go.sum
Updates dev mode to use latest refresh version `0.7.2`
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] Linux
```
| Name         | Ubuntu                             |
| Version      | 22.04                              |
| ID           | ubuntu                             |
| Branding     | 22.04.3 LTS (Jammy Jellyfish)      |
| Platform     | linux                              |
| Architecture | amd64                              |
| CPU          | AMD Ryzen 7 3700X 8-Core Processor |
| GPU 1        | Unknown                            |
| Memory       | 12GB                               |
| Wails CLI    | v3.0.0-alpha.4                           |
| Go Version   | go1.22.0                                 |
| Revision     | …
```
=> refresh version up

v3/go.mod, v3/go.sum
Description
Updates to latest refresh version to fix windows bug from recent changes
- [ X ] Bug fix (non-breaking change which fixes an issue)
Tested by user in Discord running windows 11
=> fix dev mode windows pipe

.all-contributorsrc, website/docs/community/templates.mdx
Hello, I am removing my templates (for now) because they are extremely out of date. More details can be found in the related issue. I also updated my profile info in contributor src to reflect my GH name change.
Fixes #3437 
- No testing necessary
=> removed outdated codydbentley templates

v3/pkg/application/webview_window.go, v3/pkg/application/window.go
This reverts commit 54140e9adb78d5ea380462602d9d93091bcc1ddc.
=> Revert "Remove OpenContextMenu"

mkdocs-website/docs/en/changelog.md, v3/internal/commands/bindings.go, v3/internal/flags/bindings.go
Fixes #3572
```
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
| Name              | Windows 10 Education                                                      |
| Version           | 2009 (Build: 22631)                                                       |
| ID                | 23H2                                                                      |
| …
```
=> feat: disable spinner in ci or non terminal

v3/examples/window/main.go
This example was unintentionally removed in #3508 
https://github.com/wailsapp/wails/pull/3508/files/8dddbb2cb64f183bb0aef42f6347cd2e4c72c7fb#diff-b674a54f359fbfac4b737d6e0f5a84227fb2738955c0b6831d811aa32d683c57L281-L286
=> [v3] Restore max size example
