cmd/linux.go
using lsb_release on Manjaro returns a Distributor ID of ManjaroLinux not Arch so I added ManjaroLinux to the switch statement
=> Fixed Manjaro not being detected as arch

cmd/linux.go
The existing distribution detection does not work on Arch Linux
without the `lsb-release` package installed. This patch adds
detection using `/etc/os-release` in the same way that f9a1881
uses for Fedora and CentOS detection.
I changed the if statement that Bryn Sinclair used to a case
statement to avoid extra if-else-if statements.
I also needed to add a trim statement to remove the `"` characters
that are present in Arch Linux's `/etc/os-release` file.
=> CMD: LINUX: Arch Linux detection without lsb-release

cmd/templates/create-react-app/frontend/package.json.template, cmd/templates/create-react-app/frontend/src/components/HelloWorld.js
#121  OK so after more testing whatever the problem is, it is not always reproducible.
Furthermore the problem does not seem to be with my code but npm/node.
Because this is likely to keep on happening here are some suggested steps to fix the issue whenever occurs:
1. Delete `node_modules` folder, `package.json.md5` & `package-lock.json` and run `npm install` again.
2. Create a new project `wails init`
3. if 1 didn't fix the issue and 2 is not possible then a quick & dirty fix seems to be altering `package.json` like so:
before
```json
"browserslist": {
"production": [
">0.2%",
"not dead",
"not op_mini all"
],
"development": [
"last 1 chrome version",
"last 1 firefox version",
"last 1 safari version"
]
}
```
after
```json
"browserslist": {
"production": [ ],
"development": [ ]
}
``` …
=> fix(react template): reverting bugfix + code clean-up

cmd/linux.go, cmd/system.go, cmd/wails/0_setup.go
If a distribution is unknown to Wails, the user is prompted if they'd like to submit a ticket to add support for the distribution.
=> 133 unsupported platform requests

cmd/semver.go, go.mod, go.sum
There's a double-reference in `go.mod` for `Masterminds/semver` which potentially causes the following error when compiling:
```
/go/pkg/mod/github.com/!masterminds/sprig@v2.16.0+incompatible/semver.go:4:2: case-insensitive import collision: "github.com/Masterminds/semver" and "github.com/
masterminds/semver"
```
Given that the package is (currently) stylised as `Masterminds/semver`, it's easiest to fix this by renaming our reference to the capitalised `Masterminds`.
=> Fix Masterminds/semver reference import path (case-sensitivity)

cmd/linux.go
Since `/etc/os-release` should always exist and `lsb_release` doesn't I removed it.
I changed detection from `NAME=` to `ID=` which should fit this purpose better.
Fixes #171 
I did not test anything this on any distro besides Arch Linux.
Signed-off-by: Chronophylos <nikolai@chronophylos.com>
=> Drop lsb_release

cmd/linux.go, cmd/linuxdb.yaml, cmd/system.go
Debian dependencies are sufficient to allow this to work.
Tested:
* Angular
* React
* Vuetify2
* Vuetify1.5
* Vue2
=> [326-platform-raspbian] feat: implement raspbian support

cmd/gomod.go, cmd/wails/15_migrate.go, cmd/wails/4_build.go
This PR will add the ability at compile time to update the version of Wails in go.mod. Currently it is possible to have the compiler and runtime versions out of sync, leading to some interesting side effects.
=> Ensure version in go.mod is up to date

cmd/package.go
ico generate multiple sizes (256, 128, 64, 48, 32, 16) as described in https://github.com/wailsapp/wails/issues/397#issuecomment-631412932
=> Improved Windows .ico generation

lib/interfaces/renderer.go, lib/renderer/bridge/bridge.go, lib/renderer/webview.go, lib/renderer/webview/webview.go, lib/renderer/webview/webview.h, runtime/dialog.go
References #436 
TODO
To add a file extension filter, you need to pass a comma delimited string to `SelectFile` / `SelectSaveFile` :
```go
s.runtime.Dialog.SelectSaveFile("*.jpg,*.png")
```
I added a variadic parameter to these functions to avoid a breaking change. So if you don't need any filter you can just dismiss the params.
```go
s.runtime.Dialog.SelectSaveFile()
```
@leaanthony This is an implementation for GTK only, I will work on WinAPI / Cocoa if you think the current implementation is right.
=> feat: add file extension filtering to select/save dialogs

lib/renderer/webview/webview.h
Free memory after splitting strings.
=> free filter memory

.github/workflows/latest-pre.yml, .github/workflows/pr.yml, .github/workflows/release.yml, README.md, cmd/system.go, cmd/wails/8_update.go, go.mod, go.sum, runtime/filesystem.go
- Remove mitchellh/go-homedir dependency in favor of the stdlib os.UserHomeDir (supported since 1.12)
if we can move the min go version to 1.13, we can introduce the following improvements too:
- Use os.UserConfigDir as configuration path (respects XDG user dirs with fallback on Linux, `%AppData%` on windows and `$HOME/Library/Application Support` on mac)
- Rename the config directory to wails (since its now inside a subdirectory and not on $home)
=> refactor home and config dir to stdlib, update min go ver to 1.13

lib/renderer/bridge/bridge.go
A simple fix for emitting long messages with runtime. As discussed at #469.
=> fix(bridge): fixed long message emit issue #469

lib/renderer/webview/webview.h
This adds a fix for windows apps running on hidpi screens. Currently, the size of the window can be incorrect.
=> Windows HiDPI Scaling Fix

cmd/templates/angular-template/frontend/src/app/app-routing.module.ts
As discovered in issue #497 there is an angular routing issue. This pull request fixes the template to use hash based routing to workaround the issue.
=> resolve angular routing broken when app is built

CONTRIBUTORS.md, runtime/store.go
@leaanthony this adds the possibility to use errorHandler when Set method fails while using Update method.
=> handle Set error on Update method

cmd/helpers.go, cmd/project.go, cmd/wails/4_build.go
Allows the developer to specify a `-gopath` path argument during build which is mounted to the docker container at `/go` which is configured as the GOPATH inside the runtime.
Allows the developer to specify a `-gopath` path argument during build which causes the location on your host to be mounted at `/go` inside the cross-compiler container.  
Enabling the `replace github.com/original/library => github.com/tmclane/library` style of substitution where you edit files on the host and they are made available in the cross-compile environment.
Addresses: #460
=> implement gopath handling during cross compilation

cmd/project.go, cmd/templates.go, cmd/wails/4_build.go
Supports an extra line in templates metadata:
```
"bridge": "src",
"wailsdir": "",
"platforms": ["windows"]      // Can be nil, empty, or contain any combination of "windows" "linux" "darwin"
```
Warns on init and build.
=> Support platform list in templates

cmd/templates/svelte/frontend/rollup.config.js
As described in #592 , the `spec` option leads to a failing frontend. Removing it fixes this and seems to not break anything.
=> Fix wails init failing using the Svelte template

v2/internal/html/assetbundle.go
In some bundler enviroments like vite the output on index.html uses link
tag with rel="modulepreload" to load javascript, add support to handle
this files on assetbundle, more info
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/modulepreload
this is experimental, so maybe its necessary review what types are supposed to be supported
fix #620
=> fix: V2 code gen issue

lib/binding/manager.go
Currently generated typings produce invalid TypeScript code and look  something like this:
```
Interface ServerApi {
AddNewServer: (...args : any[]) => Promise
DeleteServer: (...args : any[]) => Promise
GetExistingServers: (...args : any[]) => Promise
}
Interface Backend {
ServerApi: ServerApi
}
declare global {
interface Window {
backend: Backend;
}
}
```
First of all, some `export` is required, since augmentations of window aren't allowed otherwise (TS error). 
`interface` keyword should start with a lowercase and `Promise` should have a typed response, even if it's an `any`.
After this small change typings look like this:
```
interface ServerApi {
AddNewServer(...args : any[]):Promise<any>
DeleteServer(...args : any[]):Promise<any>
GetExistingServers(...args : any[]):Promise<any>
} …
```
=> Fixes TypeScript generated typings

v2/internal/binding/generate.go, v2/internal/binding/generate_test.go
When serializing a []byte type to json, Go actually creates a base64 encoded string, not an array of numbers. This PR updates the generated javascript types to correctly handle this case.
=> [V2] []byte type fix.

v2/pkg/options/options.go, v2/pkg/options/options_test.go
Currently if MaxWidth and MaxHeight are left as default, it causes Width and Height to be set to 0. This PR fixes this and adds tests for the width and height behaviour of MergeDefaults.
=> [V2] width height fix

v2/internal/html/asset.go, v2/internal/html/asset_test.go, v2/internal/html/assetbundle.go, v2/internal/html/assetbundle_test.go, v2/internal/html/testdata/basic.html, v2/internal/html/testdata/multi_line.html, v2/internal/html/testdata/self_closing.html, v2/internal/html/testdata/src/bundle.js, v2/internal/html/testdata/src/favicon.svg, v2/internal/html/testdata/src/style.css
I probably should have made this two PRs, but was lazy, sorry. :-/ 
This fixes two issues.
1. Multi-line tags like
```
<link
rel="foo"
href="bar"
>
```
currently get minified to something like `<linkrel="foo"href="bar>` which isn't right. To fix this I modified the magnification for html to simply replace any run of whitespace with a single space. It's certainly possible to compress more with more sophistication but given that the initial html load is generally super small probably a premature optimization.
2. The asset building doesn't catch self closing html tags like `<link rel="foo" href="foo" />`. It now works with these too. 
I've added tests for both of these cases.
=> [v2] Fixed bundling and minification.

v2/internal/ffenestri/windows/x64/x64.go, v2/internal/ffenestri/windows/x64/x64_stub.go
Howdy!
So I was on a flight and was attempting to get wails to build on my mac.
Ran in to the Windows specific code inside the `base` and just added this small hack to get it to work.
```
go build
../../internal/ffenestri/windows/x64/x64.go:5:12: pattern webview.dll: no matching files found
```
I do not really want this merged since I think a better solution should be created first.
=> hack: enable builds on non-Windows

lib/renderer/webview/webview.h
=> Fix crash on Mac save dialog when replacing file

v2/internal/html/assetbundle.go, v2/internal/html/assetbundle_test.go, v2/internal/html/testdata/inline_javascript.html
Think it would be nice to allow inline javacsript.
I've created an app via `create-react-app` and stumbled upon this. Also, I bumped into errors, when none of these conditions were met: https://github.com/wailsapp/wails/blob/v2-alpha/v2/internal/html/assetbundle.go#L97-L118
Think better error reporting might be a good idea so users can remove those `link` tags?
=> [v2] handle inline javascript in assetbundle.go

v2/internal/frontend/assetserver/mimecache.go, v2/internal/frontend/assetserver/mimecache_test.go
I was trying to setup a Vite+Vue3-TS application so I could create a template and ran into an issue with the asset server serving JS files as 'text/plain', which results in the following console error: 
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`
=> Added JS case to mimecache

v2/internal/binding/generate.go
Came across this issue when testing multiple packages and it seemed simple enough to fix
=> Fixed missing comma that breaks bindings with more than one package

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/appng/app_dev.go
use environment variables to supply the development binary with flags to support CLI arguments in the app
=> use environment variables instead of flags in dev to support CLI apps

v2/cmd/wails/internal/commands/generate/template/base/package.json
Adds a package.json with basic start / setup npm scripts to assist non golang developers working on an end project.
=> Helper NPM scripts for developers working on a Wails GUI project

v2/cmd/wails/internal/commands/generate/template/base/package.json
Running `npm install` will now run on the top level of a generated project and additionally the "frontend" workspace (we can add plugins for wails to this folder space for auto update, package, sign, publish, etc)
Other commands that use workspaces (including pre/post hooks mostly) and might be helpful to Wails are `docs`, `install`, `rebuild`, `publish`, `pkg`, `pack`, `ci`
For example, during wails build, you could ask for data from the frontend/package.json to get version, title, etc with.
`npm pkg get name version --workspace=frontend`
=> Adding workspace to npm which better integrates wails and frontend npm.

v2/internal/frontend/desktop/linux/frontend.go
This happens when building for linux. Full error before fix:
../wails/v2/internal/frontend/desktop/linux/frontend.go:331:47: cannot use uri (type *_Ctype_char) as type string in argument to common.TranslateUriToFile
gofmt reformatted a couple of comments in the fixed file too.
=> Fix error: cannot use uri (type *_Ctype_char) as type string in argument to common.TranslateUriToFile.

v2/internal/frontend/desktop/darwin/Application.h, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go
This also fixes that requests remain in "pending" state on
darwin if e.g. a file is not found or an error occurs during
loading of the file.
Fix #1003
=> [v2] Improve processRequest: Handle errors and behave more like a webserver

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/project/project.go, website/docs/guides/application-development.mdx, website/docs/guides/ides.mdx, website/docs/guides/migrating.mdx, website/docs/howdoesitwork.mdx, website/docs/reference/cli.mdx, website/docs/reference/project-config.mdx
It also contains some minor improvements for updating `wails.json` from `wails dev`.
This is a followup of #1001
=> [v2] Update docs with new assetdir management and add reloaddirs

lib/event/manager.go
Locking the event manager before mutating it. The mutex was never locked before accessing the listeners which caused a concurrency error. This should be the only thing needed to fix the error.
=> Fix for #950

v2/internal/frontend/desktop/windows/window.go
Fix bug #1049 on Windows where the disableResize option depends on the frameless option.
=> Allow window resizing regardless of frameless or other options (#1049)

v2/internal/frontend/desktop/windows/frontend.go
-  Fixes #916 
- Tested on Windows 11
Using `WindowStartState:  options.Maximised` in app options is 100% functional BUT manually setting the window state like
```
func (b *App) startup(ctx context.Context) {
runtime.WindowMaximise(ctx)
}
```
does not work.
Found out the calls to Show in [navigationCompleted](https://github.com/wailsapp/wails/blob/0d402492db8dd36d455d745ed5f7a1a980ab7000/v2/internal/frontend/desktop/windows/frontend.go#L480) were negating the maximize request in startup.
I added a navigationCompleted check in WindowMaximise and WindowMinimise for windows devices. If chromium is not ready when called, the WindowStartState will be modified before startup and ensures we do not mistakenly call a window Show an extra time.
Set the StartHidden option to true in app options & …
=> [v2] Fix: win window maximise/minimise

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/window.go
Frameless windows are always not resizable per default and
the resizing for those will be initiated by the frontend see
processMessage.
If EnableSizable is enabled for frameless windows, a small white
titlebar will be shown.
Fix #1049
=> [v2] Only call EnableSizable for normal windows

v2/internal/binding/generate.go, v2/internal/binding/generate_test.go
The `wailsjs/runtime/runtime.d.ts` already has the `window.runtime` interface exported by default. I changed one line of code to add an export for the `window.go` interface within `wailsjs/go/bindings.d.ts` for linting purposes (the compiled JavaScript previously correctly referenced `window.go` during runtime even with the linting error).
The test located in `generate_test.go` failed as well but seems to be a false positive - it seemed to give the same error both before and after the change so I fixed it. Here's the original failure output when running `go test` in the directory:
```
--- FAIL: Test_goTypeToJSDocType (0.00s)
--- FAIL: Test_goTypeToJSDocType/[]int (0.00s)
generate_test.go:83: goTypeToJSDocType() = Array<number>, want Array.<number>
--- FAIL: Test_goTypeToJSDocType/[]bool …
```
=> Added TypeScript interface export for the window.go object

v2/internal/appng/app_default_darwin.go, v2/internal/appng/app_default_linux.go, v2/internal/appng/app_production.go, v2/internal/frontend/desktop/linux/calloc.go, v2/internal/frontend/desktop/linux/dialog.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/window.go, website/docs/reference/runtime/dialog.mdx
Uses the same technique as the ExecuteJS to run the dialog code as a callback on the main thread.
Note: Only the `OpenFileDialog` is implemented at this time.
=> [linux] Fix dialogs 

v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/window.go, v2/pkg/options/windows/windows.go
Fixes #1081
Need to wait for the following PR (https://github.com/leaanthony/go-webview2/pull/5) to merge so `go-webview2` exposes the `NotifyParentWindowPositionChanged()` method.
Was not sure how to correctly expose the chromium object to the window object. Do you agree with the proposed fix? Doesn't feel really solid imo
Note: First time creating a public Pull Request, so if I can improve certain parts, please let me know :)
=> Updated windows window/frontend to fix issue with html select positioning

v2/internal/frontend/desktop/linux/frontend.go
Corrects an issue where the data being used by the webkit code was garbage-collected before it was processed.
Follows the pattern show on this [page](https://wiki.gnome.org/Projects/WebKitGtk/ProgrammingGuide/Cookbook)
=> ensure data doesn't get garbage collected too soon

v2/internal/fs/fs.go
Ran into an issue using Svelte-Kit where it creates an `index.html` page for each `route`.  This update locates the index.html with the shortest path i.e. the first one in the directory hierarchy.
Note: For Svelte-Kit you really need to use Go 1.18 beta2 and add the `all:` prefix to the `embed.FS` in the `main.go` for your application.
=> use path to first index.html file for 'index'

v2/internal/frontend/desktop/windows/window.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/options.mdx
This is a breaking change for all users of the flag.
Fix #1147
=> [v2, windows] Invert the frameless border flag and rename it

v2/cmd/wails/internal/commands/initialise/templates/templates.go
Added support for remote template versions, users can add a version identifier after the remote template to use the specified version of the template. e.g. `wails init -n Wails-Vue -t https://github.com/misitebao/wails-template-vue@v1.0.0-beta.2`
(https://github.com/wailsapp/wails/issues/925)
=> feat(cli): add version support for remote templates

v2/internal/frontend/desktop/linux/window.go
As seen in discussion https://github.com/wailsapp/wails/discussions/1156, I've noticed a few unexpected signal errors and panics when running a Wails app in NixOS.
This PR fixes the errors I've seen:
1. When quitting the app it would always fatal error because the window reference was released before destroy was called on it.
2. There was often an error related to setting the title on the window due to a race condition.
3. Clicking a blank/background area in the window caused a crash when drag move was initiated.
=> Fix linux unexpected signal errors

v2/internal/frontend/desktop/windows/frontend.go
This should allow web workers to be used
The purpose of this draft PR is to see if web workers would work as requested in #1210. I've just changed it and the vanilla template worked, I've not further tested it and I've not taken a look into all implications of this change. So the PR is open for discussions.
=> [v2, windows] Move assets from file://wails to https://wails.localhost

v2/pkg/buildassets/build/windows/installer/project.nsi, v2/pkg/buildassets/build/windows/installer/wails_tools.nsh
Especially the File directive seems not to work with a `/` on
Windows. Whereas `\` works for all directives and on all platforms.
So the `\` in NSIS can be used also on Linux and MacOS.
Closes #1226
=> [v2, nsis] Seems like `/` as path separator works only for some directives in a cross platform way

v2/internal/binding/generate.go, v2/internal/binding/generate_test.go
From the conversation on the issue #945 the generation of the file more specific here https://github.com/wailsapp/wails/issues/945#issuecomment-999378082 to avoid errors on the bindings definitions is necessary to reference the models. In order to import all the generated models it is necessary to us the `as` and give a namespace and of course it is necessary to add it to the use of the types.
=> import models on binding definition

v2/internal/frontend/desktop/linux/window.go
Resolves #1244 
The GDK_WINDOW_STATE_FULLSCREEN bitmask was not being used properly in `C.IsFullScreen`, and because other states such as GDK_WINDOW_STATE_FOCUSED could also be in play, `Window.IsFullScreen` needs to check for non-zero rather than one as the `C.IsFullScreen` result.
=> Ensure Linux IsFullScreen uses GDK_WINDOW_STATE_FULLSCREEN bitmask appropriately.

v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/window.go
cosmetic: use bodyLen instead of len() in processRequest()
=> add support for 'DomReady' callback on linux

v2/cmd/wails/internal/commands/dev/dev.go
This removes the requirement of wails being in the PATH
#1148
=> [v2] Use os.Args[0] for self starting wails

v2/internal/frontend/desktop/windows/frontend.go
This PR addresses issue #1253 .
TLDR: Basically switch to http to allow requests for insecure content
=> [v2, windows] Windows switch scheme: https -> http

v2/internal/system/packagemanager/apt.go, v2/internal/system/system.go, v2/internal/system/system_linux.go
Attempts to discover the dependencies if not installed via the package manager.
The library discovery code is untested!
=> Check system for user installed Linux dependencies 

v2/cmd/wails/internal/commands/doctor/doctor.go
Also outputs VCS information if Go 1.18+ has been used to build wails.
Issue reports often miss the information about the version of wails, because only the output of `wails doctor` is provided. This PR adds build information and version of wails to the doctor output.
=> [v2] Wails doctor add information about wails

website/docs/guides/signing.mdx, website/docs/guides/windows-installer.mdx
Hopefully this includes useful documentation for code signing Wails binaries on GitHub Actions and NSIS installers.
Closes issue #1292
=> Added docs for code-signing and NSIS installer

v2/cmd/wails/internal/version.go
Looks like the an invalid version string got merged to master.
This just removes it.
=> cleanup Version

v2/internal/frontend/desktop/windows/frontend.go
If the window is frameless and we are minimizing, then we need to suppress
the Resize on the WebView2. If we don't do this, restoring does not work as
expected and first restores with some wrong size during the restore animation
and only fully renders when the animation is done.
This highly depends on the content in the WebView.
Fixes #1319
=> [v2, windows] Suppress resizing during minimize of a frameless window

v2/internal/frontend/runtime/wrapper/runtime.js
Calls on these functions were causing "OnMultiple is not defined" errors
=> fix runtime.js events

v2/cmd/wails/internal/commands/build/build.go
- Make sure to reset the default Arch of the build options and not keep the previous one.
- Expand to the full platform in outputBinaries so e.g. `-platform windows` can be used with `-nsis`
=> [v2] Improve multi platform builds

v2/internal/frontend/assetserver/assethandler.go
This slows down every GET request to the AssetsHandler taking 5s
Proposal to fix #1380
=> [v2] During wails dev only use reload logic if no AssetsHandler are in use

v2/internal/frontend/desktop/linux/gtk.go, v2/internal/frontend/desktop/linux/window.go
=> [v2, linux] Make sure to execute the menu callbacks on a new goroutine

website/versioned_docs/version-v2.0.0-beta.35/reference/cli.mdx
For users who wish to keep the wailsjs directory out of source control, the `wails generate module` command is valuable in a CI environment where wails build does not automatically generate the needed javascript module.
=> Add docs on wails generate module

v2/cmd/wails/internal/commands/initialise/templates/generate/assets/common/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/lit-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/lit/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/preact-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/preact/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/react-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/react/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/svelte-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/svelte/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/vanilla/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/vue-ts/frontend/wailsjs/runtime/runtime.d.ts, v2/cmd/wails/internal/commands/initialise/templates/templates/vue/frontend/wailsjs/runtime/runtime.d.ts, v2/internal/frontend/runtime/wrapper/runtime.d.ts
Update `window.runtime.Environment` type
Before: 
```ts
export function Environment(): EnvironmentInfo;
```
After:
```ts
export function Environment(): Promise<EnvironmentInfo>;
```
`runtime.Environment` will returns `Promise`
=> Update runtime.d.ts & templates

website/docs/reference/menus.mdx
On macos platform, if custom the menu, we should append EditMenu to enable Cmd+C,Cmd+V,Cmd+Z... shortcut
=> docs: add macos custom menu EditMenu tips

v2/cmd/wails/internal/commands/initialise/templates/generate/assets/preact-ts/frontend/src/app.tsx, v2/cmd/wails/internal/commands/initialise/templates/generate/assets/preact/frontend/src/app.jsx, v2/cmd/wails/internal/commands/initialise/templates/generate/assets/react-ts/frontend/src/App.tsx, v2/cmd/wails/internal/commands/initialise/templates/generate/assets/react/frontend/src/App.jsx, v2/cmd/wails/internal/commands/initialise/templates/templates/preact-ts/frontend/src/app.tsx, v2/cmd/wails/internal/commands/initialise/templates/templates/preact/frontend/src/app.jsx, v2/cmd/wails/internal/commands/initialise/templates/templates/react-ts/frontend/src/App.tsx, v2/cmd/wails/internal/commands/initialise/templates/templates/react/frontend/src/App.jsx
CSS styling is not being applied to the input field in the hello world templates for React and Preact because the input tag is missing the class identifier present in the templates for the other frameworks.
=> Add missing className to input in React and Preact templates

v2/cmd/wails/internal/commands/build/build.go, v2/cmd/wails/internal/commands/dev/dev.go, v2/pkg/commands/build/base.go, v2/pkg/commands/build/build.go, website/docs/reference/cli.mdx
This pull request resolves wailsapp/wails#1425 feature request, by adding the `-race` flag to `wails build` and `wails dev` commands.
=> feature - add race detector to build & dev

v2/internal/frontend/desktop/linux/invoke.go, v2/internal/frontend/desktop/linux/window.go
Make sure no pointers to the stack are passed to g_idle_add,
because at the time the callback gets executed on the
main thread, the pointer might be invalid.
Go might have reused the stack or grown the stack and the
pointer is invalid.
The concept used on Windows has been ported to Linux.
Potential fix for #1321
=> [v2, linux] Improve switching to main thread for callbacks

v2/internal/binding/generate.go
=> Always use return in wrapped method

v2/internal/frontend/desktop/windows/frontend.go
This makes sure the OSThread can be reused by other go
routines after a native call has been finished. Otherwise the
OSThread will be destroyed as soon as the goroutine has
finished.
=> [v2, windows] Unlock OSThread after native calls have been finished

v2/internal/system/packagemanager/apt.go
A minor change to correct the order of parameters to the `apt` command.
Proof of fix:
_Before:_
```
$ wails doctor
Wails CLI v2.0.0-beta.37
Scanning system - Please wait (this may take a long time)...Failed.
ERROR: exit status 1
If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
_After:_
```
Wails CLI v2.0.0-beta.37
Scanning system - Please wait (this may take a long time)...Done.
System
------
OS:		Linux Mint
Version: 	20.3
ID:		linuxmint
Go Version:	go1.18
Platform:	linux
Architecture:	amd64
Wails
------
Version: 		v2.0.0-beta.37
Package Manager: 	apt
Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.17
gcc		build-essential		Installed …
```
=> Fix apt command syntax (#1458)

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/win32/consts.go, v2/internal/frontend/desktop/windows/win32/window.go, v2/internal/frontend/desktop/windows/window.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx
Sets window background colour if provided.
Added `ResizeDebounceMS` for specifying the delay before redraw when resizing.
This PR provides options to decrease the "flicker" when resizing the app on Windows.
=> Set Window Background colour if provided + debounce redraw option

v2/cmd/wails/internal/commands/generate/template/base/main.tmpl.go, v2/cmd/wails/internal/commands/initialise/templates/generate/plain/main.tmpl.go, v2/cmd/wails/internal/commands/initialise/templates/templates/plain/main.tmpl.go, v2/internal/frontend/desktop/darwin/window.go, v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/window.go, v2/internal/menumanager/processedMenu.go, v2/pkg/options/options.go, v2/wails.go, website/docs/reference/options.mdx
The option `RGBA` is too ambiguous!
=> Add `BackgroundColour` and deprecate `RGBA`

v2/internal/frontend/desktop/windows/win32/window.go, v2/internal/frontend/desktop/windows/window.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx
Added these so that an application developer can choose to do things like teardown/standup network connections on suspend/resume.
=> [Windows] Add Suspend/Resume callback support

v2/cmd/wails/internal/commands/generate/module.go
=> Bugfix: Don't stop if unable to remove temporary bindings build

v2/internal/appng/app_bindings.go, v2/internal/appng/app_dev.go, v2/internal/appng/app_production.go, v2/internal/signal/signal.go, v2/wails.go
Noticed `ctrl-c` isn't handled and leads to ungraceful shutdown.
=> Better signal handling

v2/cmd/wails/internal/commands/dev/dev.go, v2/cmd/wails/internal/commands/dev/dev_other.go
- Make sure to kill the debug process in all cases even if an error occurred
- Make sure to kill the last started binary process
- Improve starting of dev watcher command
=> [v2] Improvements to the dev command

v2/cmd/wails/internal/commands/dev/dev.go, v2/internal/appng/app_dev.go
Resolves #1533 
This change allows `-appargs` to pass flags to the binary when using `wails dev`.
This is needed because if you do not set "assetdir" in `wails.json` then the `App` created by `wails dev` tries to check the command line flags for `-assetdir` and a few more flags, and then fails when it finds the app specific flag being passed on the command line which is unknown to the flagset being used in the dev `CreateApp`.
The only way I could figure out to achieve this was to use a distinct FlagSet and set it to continue on error. I think this is ok as it only applies to running via `wails dev`, but wouldn't be too upset if someone has a better solution! :smile: 
There's a bonus typo fix in the help message for `-appargs` and gofmt fixes included for good measure too.
=> Allow -appargs flag to pass flags to binary.

v2/cmd/wails/internal/commands/doctor/doctor.go, v2/internal/system/packagemanager/nixpkgs.go, v2/internal/system/packagemanager/packagemanager.go, v2/internal/system/packagemanager/pm.go, v2/internal/system/system.go, v2/internal/system/system_darwin.go, v2/internal/system/system_linux.go, v2/internal/system/system_windows.go, website/docs/guides/linux-distro-support.mdx
Resolves #1550 
Now `wails doctor` works on NixOS:
```
ian@ians-tuxedo:~ $ wails doctor
Wails CLI v2.0.0-beta.38
Scanning system - Please wait (this may take a long time)...Done.
System
------
OS:             NixOS
Version:        22.11
ID:             nixos
Go Version:     go1.17.11
Platform:       linux
Architecture:   amd64
Wails
------
Version:                v2.0.0-beta.38
Package Manager:        nixpkgs
Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         nixos.docker    Installed       20.10.17
gcc             nixos.gcc       Installed       11.3.0
libgtk-3        nixos.gtk3      Installed       3.24.34
libwebkit       nixos.webkitgtk Installed       2.36.4
npm             nixos.nodejs    Installed …
```
=> Add nixpkgs support to doctor command.

v2/internal/appng/app_production.go, v2/pkg/options/default.go, v2/pkg/options/options.go, website/docs/reference/options.mdx
Allows the developer to set the log level when running in production. Currently hardcoded to `ERROR`.
=> Add support for production log levels

v2/internal/project/project.go, v2/pkg/commands/build/build.go, website/docs/reference/project-config.mdx
Adds a "preBuildHooks" option which runs before any builds. Supports different platforms & architectures.
Fixes #1577
=> Add pre-build hooks. Print command output when verbosity flag set.

v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2HttpHeadersCollectionIterator.go
The API expects a `BOOL *` with `typedef int BOOL` therefore
we need to use a `int32` on the stack.
Fixes #1584
=> [windows] Fix stack corruption when using ICoreWebView2HttpHeadersCollectionIterator

website/docs/howdoesitwork.mdx
This fixed a small typo on the page https://wails.io/docs/howdoesitwork. For whatever reason, the word "it's" was spelled incorrectly to "it''s". 
This typo seems to have been introduced in: https://github.com/wailsapp/wails/commit/f21c9ba88031d0fbc2faaa4a4799566c757839f3
=> :memo: Fixed typo in documentation page docs/howdoesitwork

website/versioned_docs/version-v2.0.0-beta.40/guides/manual-builds.mdx
`go build -tags desktop,production -ldflags "-w -s -H windowsgui"` returns an error on MacOS/Linux.
It is referenced in Wails CLI that manually only `-w -s` are passed by default.
=> Generalize manual compile steps [Documentation]

v2/cmd/wails/internal/commands/dev/dev.go
Otherwise we can't use `wails dev` for projects where `wails build` works, e.g. on the plain template.
=> [dev] Ignore empty install command, we also do ignore it during the build step

v2/internal/frontend/desktop/windows/dialog.go, v2/internal/frontend/desktop/windows/win32/consts.go, v2/internal/frontend/desktop/windows/win32/window.go, v2/internal/frontend/desktop/windows/window.go
On Windows, if the window has not yet been activated, calls to dialog methods will crash due to some weirdness deep inside a windows syscall. This PR will use the desktop (nil HWND) if the window is not visible. Fixes #1660
=> Windows dialogs - Handle scenario when window is not visible yet.

v2/internal/frontend/desktop/darwin/frontend.go
There's no guarantee that the pointer is still valid when
processURLRequest is finished. So we might end up with an
invalid pointer when the request is asynchronously processed.
Fixes #1664
=> [v2, darwin] Make sure to copy the uri during processURLRequest

v2/internal/system/operatingsystem/os_darwin.go
It seems like kern.osrevision is always 199506 since several years
and kern.osversion maps to the official documented build id.
Example: MacOS 12.5 with ID 21G72
=> [v2, darwin] Use kern.osversion for os id in doctor

v2/internal/frontend/desktop/darwin/Application.h, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/darwin/main.m, v2/internal/frontend/desktop/darwin/message.h
This makes sure we always use the correct WKURLSchemeTask during
processURLResponse. Only using the URL is not unique enough and
might result in pending requests if two requests with the same URL
are getting processed.
Fixes #1672
=> [v2, darwin] Assign a unique requestId to every WKWebView request

v2/pkg/commands/build/base.go
This seemed to work for Go < 1.19 but since 1.19 this gives
an error.
Fixes #1688
=> [v2, build] gcflags don't need to be quoted

v2/internal/binding/binding.go, v2/internal/binding/generate_test.go
=> Fix registration of exposed fields

website/docs/guides/routing.mdx
doc: add react-router to routing.mdx
=> doc: add react-router to routing.mdx

v2/internal/frontend/desktop/linux/frontend.go
The existing logic always sets the `GDK_BACKEND` variable to `x11`, which prevents the application from using the wayland backend (or running at all in a wayland compositor if xwayland is unavailable). The reason this logic is present is because windows would fail to centre without it, so we need to keep the behaviour in x11 sessions.
The `GDK_BACKEND` variable can and typically should remain unset in a wayland session, and the `XDG_SESSION_TYPE` variable is usually set and can have a value of `unspecified`, `tty`, `x11`, `wayland` or `mir`.
The logic in the patch is as follows; if the system has already set the `GDK_BACKEND` variable, we should assume that it knows what it's doing and keep the existing value. If the `GDK_BACKEND` variable is empty however, we check to see if the …
=> Only set GDK_BACKEND to "x11" if GDK_BACKEND is unset and XDG_SESSION_TYPE is not "wayland"

v2/internal/frontend/desktop/windows/win32/window.go
Introduced in 70c484f60317b3e2d50d154025869b3e6b9fe7d9
Until these duplicate defs are removed, bleeding edge Windows build fail with:
```
Build command: go build -trimpath -tags desktop,production -ldflags -w -s -H windowsgui -o /app/build/bin/app.exe
Environment: HOSTNAME=e7e5205f866a PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GOPATH=/go PWD=/app GOLANG_VERSION=1.19 GOOS=windows GOARCH=amd64
go list error: exit status 2: # github.com/wailsapp/wails/v2/internal/frontend/desktop/windows/win32
wails/v2/internal/frontend/desktop/windows/win32/window.go:18:2: WS_MINIMIZE redeclared in this block
wails/v2/internal/frontend/desktop/windows/win32/window.go:16:2: other declaration of WS_MINIMIZE …
```
=> Remove duplicate defs in win32/window.go

v2/cmd/wails/internal/commands/build/build.go, v2/cmd/wails/internal/commands/build/gomod.go, v2/cmd/wails/internal/commands/dev/dev.go, v2/cmd/wails/internal/commands/initialise/initialise.go, v2/internal/gomod/gomod.go, v2/internal/gomod/gomod_test.go, v2/internal/goversion/build_constraint.go, v2/internal/goversion/min.go, v2/wails.go
- Update out of sync go.mod with minimum go version
- Check for minimum go version during build with build constraint
“internal/goversion/build_constraint.go:9:2: MinGoVersionRequired (constant "You need Go 1.18 or newer to compile this program" of type string) is not used”
=> [cli] Add check for minimum required go version

v2/internal/frontend/desktop/windows/dialog.go, v2/internal/frontend/desktop/windows/dialog_test.go, website/docs/reference/runtime/dialog.mdx
Adds support for specifying that the "No" button is default when opening a question dialog on Windows.
Example:
```go
result, err := runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
Type:          runtime.QuestionDialog,
Title:         "Question",
Message:       "Do you want to continue?",
DefaultButton: "No",
})
```
Fixes #1871
=> Add support for default No button

v2/pkg/commands/build/base.go, v2/pkg/commands/build/base_test.go
Generates better output when using `-v 2`.
Before:
` Build command: go build -tags desktop,production -ldflags -w -s -H windowsgui -o default_no.exe`
After:
` Build command: go build -tags desktop,production -ldflags "-w -s -H windowsgui" -o default_no.exe`
Fixes: #1885
=> Quote command arguments if they have a space

v2/cmd/wails/internal/commands/dev/dev.go
Adds support for watching for creation of new files while running `wails dev`.
I encountered a bug where updates to my `go` files were not resulting in a refresh of the wails app.
I added some logging to see what events were coming out of `fsnotify` and I found that when I wrote updates to my code, fsnotify was picking up a sequence of `REMOVE` `CREATE` `CHMOD` events instead of a `WRITE` as this code was expecting.
Tested and working on macOS 12.4.
```
FSNotify Event Item:  "/Users/scottopell/dev/heaprof/app.go": REMOVE
FSNotify Event Item:  "/Users/scottopell/dev/heaprof/app.go": CREATE
FSNotify Event Item:  "/Users/scottopell/dev/heaprof/app.go": CHMOD
```
=> Fix for considering new `go` files in dev filesystem watcher

website/docs/community/templates.mdx
This template is for folks looking to use Elm and Tailwind CSS to develop their Wails app. Supports hot reloading 🎉
=> Add Elm Tailwind CSS community template

v2/internal/binding/binding.go, v2/internal/binding/binding_test/binding_multiplestructs_test.go, v2/internal/binding/binding_test/binding_test.go
Sorts the structs alphabetically in `models.ts`
Fixes #1958
=> Sort structs in models.ts. 

v2/cmd/wails/internal/commands/initialise/initialise.go
=> fix: init command not listed in wails help message

v2/internal/frontend/desktop/windows/window.go
MonitorFromWindow is unreliable during a maximize, it might return the wrong monitor for the window or can't find one. As a result the webview2 remains blank/white.
See also https://github.com/MicrosoftEdge/WebView2Feedback/issues/2549
Fixes #2042
Fixes #1941
=> [windows] Fix frameless maximizing in multi monitor setup

website/docs/community/templates.mdx
I added two new community templates based on [quasar](https://quasar.dev/)
Quasar has quite a few configuration options so these templates use relatively "safe/standard" defaults.
There is one template for JavaScript and one for TypeScript.
=> Added quasar-js and quasar-ts templates

v2/internal/frontend/desktop/darwin/inspector.go, v2/internal/frontend/desktop/darwin/inspector_dev.go, v2/internal/frontend/desktop/darwin/window.go, v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/corewebview2.go, v2/pkg/options/debug.go, v2/pkg/options/options.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
Some known limitations
- The initial selected tab depends on the platform implementations. (macOS, Windows: Network-Tab, Linux: Sources-Tab) 
- The inspector is always in foreground
- Network records might be missing for the first load.
Fixes #2059 
Tested on:
=> [debug] Introducing debug options for debug builds to allow opening the inspector on startup

website/docs/guides/local-development.mdx
It's the local development setup guide so let's rename it.
=> Rename bleeding edge -> local development

v2/internal/frontend/assetserver/assethandler.go, website/src/pages/changelog.mdx
This allows streaming audio and videos with range requests if the platform webview supports it.
=> [assetserver] Add support for range requests if the fs.FS provides an io.Seeker

README.ja.md, README.ko.md, README.zh-Hans.md
Hi! 
I want to add korean version README.md documents. So I requested!
- Add korean version README
- Update 'README.ko.md' linked in README.md
I love the Go language and was happy to come across Wails while looking for an alternative to heavy Electron.
Thanks! Also, I will update the Korean version of the manual through __crowdin__ whenever the time is right.
Bye! 🎈
=> docs: Add README.ko.md

v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium_386.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium_amd64.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium_arm64.go, v2/internal/frontend/desktop/windows/window.go, website/src/pages/changelog.mdx
This seems to be only a problem on some Windows versions.
Fixes #2108
=> [windows] Prevent a thin white line at the bottom of a frameless window

v2/internal/app/app_dev.go, v2/internal/frontend/assetserver/assethandler.go, v2/internal/frontend/assetserver/assetserver.go, v2/internal/frontend/assetserver/common.go, v2/internal/frontend/devserver/devserver.go, v2/internal/fs/fs.go, v2/pkg/options/assetserver/options.go, website/src/pages/changelog.mdx
Furthermore this PR improves some error messages for the AssetServer Options and adds some additional checks. 
Fixes #2109
=> [assetserver] Add support for serving the index.html file when requesting a directory

v2/internal/frontend/desktop/linux/frontend.go, website/src/pages/changelog.mdx
This PR sets up a new signal handler in C that overrides the current one (in C) so that `SA_ONSTACK` is used. When used against the nil dereference example @mholt gave, it appears to work as expected.
Closes #2134
=> Fix signal handler

v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/webkit2.go, v2/internal/frontend/desktop/linux/webkit2_36.go, v2/internal/frontend/desktop/linux/webkit2_legacy.go, v2/internal/frontend/desktop/linux/webkit2_responsewriter.go, v2/internal/frontend/desktop/linux/window.go, v2/pkg/options/linux/linux.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
=> [linux] Add support for WebKit2GTK 2.36+ features

v2/examples/customlayout/myfrontend/src/main.js
Commonly expected UX on inputs is to handle submit on enter key.
Attached an event listener on the document to call `window.greet()` on `keydown` for enter key.
=> examples/customlayout: feature: add event listener for enter key

v2/pkg/menu/styledlabel.go
Updated to remove only one line of `unreachable` code.
=> go vet cleanup

v2/internal/platform/systray.go, v2/internal/platform/systray/systray_mac.go
Unit tests are broken after https://github.com/wailsapp/wails/commit/b84a2e52553463fc743b4e4b4e587734eed1ee52 because it has build restriction only for windows.
This PR is fixing tests for MacOS by adding Systray structure that will produce NotImplemented error if someone try to use it on Mac; however it still be buildable and testable.
=> Add dummy systray_mac to fix unit tests

v2/internal/frontend/desktop/linux/window.go, v2/internal/platform/systray.go, v2/internal/platform/systray/systray_linux.go
Allows the right mouse button event through whilst retaining the existing functionality of showing no context menu.
@mholt - please let me know if this fixes your issue 👍 
Also fixes the systray experiment compile issues on linux
=> [Linux] Fix right mouse button event

v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/create_env_go.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/create_env_native.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/env_create.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/env_create_completed.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/env_create_options.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/find_dll_installed.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/native_module.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/native_module_386.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/native_module_amd64.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/native_module_arm64.go, v2/internal/frontend/desktop/windows/go-webview2/webviewloader/version.go, v2/pkg/commands/build/build.go, website/src/pages/changelog.mdx
Default webview2loader is now the go loader
=> [webview2loader] Promote go loader from experimental to stable

v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, website/src/pages/changelog.mdx
This will show a message on the console
"+[CATransaction synchronize] called within transaction" but there's seem no way to mitigate that. Still everything works as expected.
Fixes #1331
=> [darwin] Add support for file input selection

v2/cmd/wails/build.go, v2/cmd/wails/flags/buildcommon.go, v2/cmd/wails/internal/dev/dev.go, v2/internal/gomod/gomod.go, v2/internal/gomod/gomod_data_unix.go, v2/internal/gomod/gomod_data_windows.go, v2/internal/gomod/gomod_test.go, website/docs/reference/cli.mdx
This is an alternative approach to not having the go.mod synced to your wails CLI version. It fixes the tests on master.
@mholt - could you please confirm this works for you? Adding `-nosyncgomod` to `dev` or `build` should trigger it 👍
=> Add nosyncgomod flag

v2/internal/system/packagemanager/dnf.go
(added a new commit in response to member comment)
Without this change, wails doctor reports libwebkit not being installed (even though it already is)
Old version of libwebkit has been retained for backwards compatibility
=> Update libwebkit package name for Fedora

website/src/api/crowdin.js
This just refactors the way `crowdin` initialised, to not throw away from the docs build time should there be no personal token in env variables.
If there is no token, it will log a warning message, but the rest of the functionality is available to the developer to keep on contributing
=> Improve `crowdin` init to be able to work locally

v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/create_env_go.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/create_env_native.go, v2/pkg/options/default.go, v2/pkg/options/linux/linux.go, v2/pkg/options/options.go, v2/pkg/options/windows/windows.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
This PR adds support for webview GPU settings on Windows and Linux as discussed in issue #2264.
**Windows:**
- Created a new option `WebviewGpuIsDisabled` in windows.Options
- Modified the new webview loader to be able to accept chromium switches.
- When `WebviewGpuIsDisabled` set to true the webview will be initialized with the `--disable-gpu` switch.
**Linux:**
- Created a new option `WebviewGpuPolicy` in linux.Options.
- Created a new type `WebviewGpuPolicy` and three constants to be used as options.
- WebviewGpuPolicyAlways
- WebviewGpuPolicyOnDemand
- WebviewGpuPolicyNever
- When the webview is set up the hardware acceleration policy is set based on the option. The default setting is WebviewGpuPolicyAlways, if it is not a valid option for the system GTK ignores it and sets an …
=> Support GPU acceleration settings on Windows & Linux

v2/internal/frontend/desktop/darwin/Application.h, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/main.m, v2/internal/frontend/desktop/darwin/window.go, v2/internal/frontend/desktop/windows/frontend.go, v2/pkg/options/options.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
This allows to explicitly opt-in to scan services for fraudulent
content, such as malware or phishing attempts.
Fixes #2163
=> Add EnableFraudulentWebsiteDetection to options

v2/pkg/commands/build/build.go, website/src/pages/changelog.mdx
This PR fixes #2224.
Check the existence of build/bin directory and create it if needed before running build hooks.
=> fix missing bin dir on build hook

website/docs/reference/cli.mdx
fix admonitions syntax in `/docs/reference/cli.mdx`
=> docs: fix admonitions syntax

v2/internal/frontend/desktop/linux/window.c, v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/linux/window.h
In this PR I moved the C code from v2/internal/frontend/desktop/linux/window.go to its own separate window.c and window.h files.
- I tried to reorganize the C code to make it a bit more readable.
- Moved the typedefs to the window.h file to both window.go and window.c can access them.
- Changed the function names to make them "consistent":
- functions called from window.go start with an uppercase letter.
- functions only called from window.c start with a lowercase letter and made them static.
I did not change the functionality, only the structure and the formatting of the code.
=> linux separate window c and go file

v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/winc/form.go, v2/internal/frontend/desktop/windows/window.go, website/src/pages/changelog.mdx
- In fullscreen the taskbar was not fully covered when previously maximized
- Unfullscreen did not correctly relayout the content
- Prevent Unmaximise/Unminimise when in fullscreen mode
- Use POPUP style for fullscreen mode
=> [windows] Improve fullscreen mode for frameless windows

v2/internal/frontend/desktop/windows/win32/window.go, v2/internal/frontend/desktop/windows/window.go, website/src/pages/changelog.mdx
Otherwise this leads to thin transparent lines on the window borders on older Windows versions.
=> [windows] Disable frameless decorations during fullscreen

v2/internal/frontend/desktop/windows/winc/form.go, v2/internal/frontend/desktop/windows/window.go, website/src/pages/changelog.mdx
- Do not show a white border for windows in fullscreen mode and when DisableWindowIcon is used
- Prevent a short showing of the window titlebar for frameless window when switching fullscreen/unfullscreen
=> [windows] Some improvements to fullscreen

v3/pkg/application/systemtray_darwin.go
alloc should always be paired with autorelease if not running in ARC mode.
Resolves https://github.com/wailsapp/wails/issues/2321
Related: https://github.com/fyne-io/systray/pull/34
=> Fix memory leak on Darwin when toggling system tray icon

v2/internal/frontend/desktop/windows/winc/controlbase.go, v2/internal/frontend/desktop/windows/winc/utils.go
Possible fix for #2023 and #2297.
=> Size() calculates DPIs back to default space.

website/docs/guides/dynamic-assets.mdx, website/docs/howdoesitwork.mdx
Code reviewed the entire site's code blocks for those that use a highlight. Found 3 that needed adjusting. 
Only other change was from the Markdown linter which prefers underscores for italic text instead of asterisks for some reason. Either are allowed and assuming we all use the same linter I allowed the linter's opinionated change. 
Did not see an AUTHORS.md to add to; if you need that to maintain MIT let me know and we'll add it.
=> Fix #2280 - code block highlights

v2/pkg/assetserver/mimecache.go, v2/pkg/assetserver/mimecache_test.go, website/src/pages/changelog.mdx
=> [assetserver] Add more builtin mimetypes by extension

v2/internal/frontend/desktop/darwin/inspector_dev.go, website/src/pages/changelog.mdx
Log if the inspector could not be opened due to missing or incorrect private API.
Fixes #2394
=> [darwin] Add a macOS version guard for opening the web inspector

v2/internal/frontend/desktop/darwin/WailsMenu.m, website/src/pages/changelog.mdx
I could only test it on the following config since I have no mac available with an older XCode or OS.
```
OS           | MacOS
Version      | 13.2.1
ID           | 22D68
Xcode command line tools  | N/A          | Installed | 2396
*Xcode                    | N/A          | Installed | 14.2 (14C18)
```
Fixes #2356
=> [darwin] Fix undo/redo

v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/corewebview2.go, website/src/pages/changelog.mdx
The old error handling fails on WebView2Runtimes > 110.0.1587.69 and will show a "connection refused" page and reloads after a short time. After the reload everything wroked as expected again.
=> [webview2] Fix error handling in CreateWebResourceResponse

website/versioned_docs/version-v2.4.0/guides/routing.mdx
just came across this broken link reading through the docs
=> docs: fix broken link for react router HashRouter

v2/cmd/wails/main.go, v2/pkg/commands/build/build.go
Fix console printing.
Old:
```
$ wails generate template -name VT -frontend ./vue-project/
DEB | Using go webview2loader
• Extracting base template files...  • Migrating existing project files to frontend directory...  • Updating package.json data...  • Renaming package.json -> package.tmpl.json...  • Updating package-lock.json data...  • Renaming package-lock.json -> package-lock.tmpl.json... ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
New:
```
$ wails generate template -name VT -frontend ./vue-project/
DEB | Using go webview2loader
• Extracting base template files...
• Migrating existing project files to frontend directory...
• Updating package.json data...
• Renaming package.json -> …
```
=> fix(cli): fix console printing

v2/internal/system/system.go, v2/internal/system/system_darwin.go, v2/internal/system/system_linux.go, v2/internal/system/system_windows.go, website/src/pages/changelog.mdx
- Test
Resolve: https://github.com/wailsapp/wails/issues/2537
Preview:
```
$ wails doctor
DEB | Using go webview2loader
Wails CLI v2.4.1
Scanning system - Please wait (this may take a long time)...Done.
OS           | Windows 10 Pro
Version      | 2009 (Build: 19045)
ID           | 22H2
Go Version   | go1.20
Platform     | windows
Architecture | amd64
Version  | v2.4.1
Revision | 2a22933220a57eb34b461fa97a2b53026859c736
Modified | true
Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 111.0.1661.54
Nodejs     | N/A          | Installed | 18.14.2
npm        | N/A          | Installed | 9.5.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency
Your system is ready for Wails development!
Optional …
```
=> feat(cli): add Nodejs version in `wails doctor`

v2/pkg/assetserver/webview/request_linux.go, v2/pkg/assetserver/webview/webkit2_36+.go, v2/pkg/assetserver/webview/webkit2_36.go, v2/pkg/assetserver/webview/webkit2_40+.go, v2/pkg/assetserver/webview/webkit2_40.go, v2/pkg/assetserver/webview/webkit2_legacy.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
This brings support for HTTP Request Bodies on the AssetServer
=> [assetserver, linux] Add support for WebKit2GTK 2.40+ features

v2/internal/system/packagemanager/zypper.go, website/src/pages/changelog.mdx
- Add package(webkit2gtk3-soup2-devel) for `libwebkit`.
- Add package(pkgconf-pkg-config) for `pkg-config`.
- Change environment variable before running command to query information of the package.
=> Update zypper.go (opensuse-tumbleweed)

v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go, website/src/pages/changelog.mdx
I came across a bug where unicode values such as 🫣 would not get correctly escaped. This is due to using `strconv.Quote` which would encode this value as "\U0001fae3" which is not a valid js string. This would, in turn, get turned into "U0001fae3" in the frontend.
To correctly represent these values we need to use the new js format for multi-rune characters "\u{0001fae3}"[1], but I thought, instead of figuring out the correct quoting strategy, why not just use `json.Marshal` here instead. Certainly open to finding a different approach if you don't think this is a good idea.
Also decided to panic on error here as this error should never come up, and I saw similar panics in the code encountering things like this.
[1] https://exploringjs.com/es6/ch_unicode.html#sec_escape-sequences
=> Use json.Marshal instead of strconv.Quote to correctly support unicode

v2/internal/frontend/desktop/windows/dialog.go, v2/internal/frontend/desktop/windows/window.go, website/src/pages/changelog.mdx
Otherwise it might have some strange side-effects like blocking the completion of Deferrals in WebView2 when using custom IStreams.
=> [v2, windows] Make sure to open the CommonFileDialogs on the main thread

v2/cmd/wails/internal/dev/dev.go, v2/cmd/wails/internal/dev/stdout_scanner.go, v2/examples/customlayout/myfrontend/package.json, v2/internal/app/app_dev.go, v2/internal/frontend/devserver/devserver.go, v2/pkg/assetserver/assethandler_external.go, v2/pkg/templates/templates/svelte-ts/frontend/package.json, v2/pkg/templates/templates/svelte/frontend/package.json, v2/pkg/templates/templates/vanilla-ts/frontend/package.json, v2/pkg/templates/templates/vanilla/frontend/package.json, website/src/pages/changelog.mdx
This fixes some long-standing inconsistencies between dev mode builds and production builds but is a breaking change.  Dev mode uses custom scheme for Vite versions >= 3.0.0 and for older it still behaves in the old way.
Relates to
- #2590
- #2523
- #2090
- #2026
- #1568
=> [v2, dev] Use custom schemes for in-app dev mode

v2/internal/frontend/desktop/darwin/Role.h, v2/internal/frontend/desktop/darwin/WailsMenu.m, v2/pkg/menu/menuroles.go, v2/pkg/options/options.go, website/src/pages/changelog.mdx
=> [v2, darwin] Add some missing default shortcuts

v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/COREWEBVIEW2_PROCESS_FAILED_KIND.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2ProcessFailedEventArgs.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/ICoreWebView2ProcessFailedEventHandler.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/chromium.go, v2/internal/frontend/desktop/windows/go-webview2/pkg/edge/corewebview2.go, v2/pkg/options/windows/windows.go, website/src/pages/changelog.mdx
This should help for all those issue where no Window comes up:
- https://github.com/wailsapp/wails/discussions/2621
- https://github.com/wailsapp/wails/issues/2615
- https://github.com/wailsapp/wails/issues/2529
- https://github.com/wailsapp/wails/issues/2124
=> [v2, windows] Handle webview2 process crashes and add DisableWebViewRendererCodeIntegrity flag

v2/cmd/wails/doctor.go
<details>
<summary>Preview</summary>
</details>
=> feat(cli): use Spinner instead of Print

v2/cmd/wails/internal/dev/dev.go, v2/internal/app/app_dev.go, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/windows/frontend.go, v2/internal/frontend/devserver/devserver.go, v2/pkg/assetserver/assetserver.go, v2/pkg/assetserver/assetserver_dev.go, v2/pkg/assetserver/webview/request_darwin.go, v2/pkg/assetserver/webview/webkit2_legacy.go, website/src/pages/changelog.mdx
DevServer improvements and fixes
Fixes #2661
Fixes #2667
=> [v2] DevServer improvements and fixes

v2/internal/frontend/desktop/linux/keys.go, website/src/pages/changelog.mdx
On Linux, the keys could be empty. This adds a check to skip getting `key[0]` when this happens/
Fixes this error:
```
DEBUG | Log dir is: /root/.config/surrealdb_explorer/log.txt
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.parseKey({0x0, 0x0})
/home/aminya/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/keys.go:87 +0xa5
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.acceleratorToGTK(0xc0001c5f20)
/home/aminya/go/pkg/mod/github.com/wailsapp/wails/v2@v2.5.1/internal/frontend/desktop/linux/keys.go:72 +0x2c …
```
=> fix: avoid app crashing when the Linux GTK key is empty

.github/workflows/format-markdown-files.yml, .prettierignore, .prettierrc.yml, Taskfile.yaml, v2/.prettierignore, v2/.prettierrc.yml, v2/Taskfile.yaml, v3/.prettierignore, v3/.prettierrc.yml, v3/Taskfile.yaml, website/.prettierignore, website/Taskfile.yml, website/prettier.config.js
Add `Prettier` tool to the root directory of each major version and its corresponding `website` directory to format all `.md` and `.mdx` files. However, to reduce unnecessary work, all files synchronized by Crowdin are ignored because formatting these files is meaningless.
=> chore: add `Prettier` as format tool

v2/examples/customlayout/build/windows/installer/project.nsi, v2/pkg/buildassets/build/windows/installer/project.nsi, website/src/pages/changelog.mdx
Enable Hi-DPI support for NSIS installer on windows, fix low resolution installer.
https://nsis.sourceforge.io/Reference/ManifestDPIAware
In before
After the option (text is more clear)
=> windows/nsis: add hidpi support for nsis installer

v2/pkg/templates/generate/assets/lit-ts/frontend/index.tmpl.html, v2/pkg/templates/generate/assets/lit/frontend/index.tmpl.html, v2/pkg/templates/generate/assets/svelte-ts/frontend/index.tmpl.html, v2/pkg/templates/generate/assets/vue-ts/frontend/index.tmpl.html, v2/pkg/templates/generate/assets/vue/frontend/index.tmpl.html, v2/pkg/templates/templates/lit-ts/frontend/index.tmpl.html, v2/pkg/templates/templates/lit-ts/frontend/src/my-element.ts, v2/pkg/templates/templates/lit/frontend/index.tmpl.html, v2/pkg/templates/templates/lit/frontend/src/my-element.js, v2/pkg/templates/templates/plain/frontend/src/main.js, v2/pkg/templates/templates/svelte-ts/frontend/index.tmpl.html, v2/pkg/templates/templates/vue-ts/frontend/index.tmpl.html, v2/pkg/templates/templates/vue-ts/frontend/src/main.ts, v2/pkg/templates/templates/vue/frontend/index.tmpl.html, v2/pkg/templates/templates/vue/frontend/src/main.js
Templates have been updated to include an explicit import for `style.css`.
Fixes #2705
=> [v2 templates] Add explicit style import

v2/internal/app/app_dev.go, v2/internal/app/app_production.go, v2/internal/frontend/dispatcher/calls.go, v2/internal/frontend/dispatcher/dispatcher.go, v2/pkg/options/options.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
When a call from the frontend to the backend returns an error, this change allows the formatting of the error to be customized. This allows for preserving the structure of the error in cases where the error is providing information the frontend needs to act on.
Fixes #2569
I've been running this for a while with my own app. Testing is pretty straightforward - I override the error formatter with one that formats the error as a JSON object then use that object on the frontend.
I don't know why this says my system is missing dependencies. Wails definitely works.
<pre>
OS           | Gentoo  
Version      | 2.13    
ID           | gentoo  
Go Version   | go1.19.2
Platform     | linux   
Architecture | amd64   
Version         | v2.4.1 …
=> Override error formatting

v2/internal/system/packagemanager/dnf.go, website/src/pages/changelog.mdx
This pull request added the current package names for NPM and Docker for Fedora 38.
Fixes #2638 
=> chore: update npm and docker package names for dnf package manager

website/docs/guides/application-development.mdx, website/docs/guides/sveltekit.mdx, website/versioned_docs/version-v2.4.0/guides/application-development.mdx, website/versioned_docs/version-v2.5.0/guides/application-development.mdx
This PR adds detailed documentation on the configuration required to run a `Wails` project built with a CRA frontend in watch mode to enable hot-reloading.
Tested in a local project on macOS
=> Create-React-App documentation updates

v2/internal/frontend/desktop/linux/frontend.go, v2/pkg/options/linux/linux.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
When the program's executable name differs from the human readable name in a .desktop file sometimes the window manager won't draw the correct icon for it and if multiple instances are running the grouping can be weird too.
This PR aims to help with this issue by adding a new linux application option named `ProgramName`. This value is set when a new frontend instance is created by calling GTK's g_set_prgname() function.
Fixes #2800 (issue)
Tested on existing and on newly created applications by creating different .desktop files with program names icons and executable filenames.
Tested on: Ubuntu 22.04.3 LTS, Ubuntu 23.04, !Pop_OS 22.04
Wayland and X11
```shell
OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version …
```
=> add new programName option to linux options

v2/internal/frontend/desktop/linux/window.c, v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/linux/window.h, website/src/pages/changelog.mdx
With this PR the `SetBackgroundColour` function sets the window's and the webview's background color as well. To make the resize flickering less prominent.
Fixes #2852 
Tested it on existing and new projects, set the color from go and javascript.
```shell
OS           | Ubuntu  
Version      | 23.04   
ID           | ubuntu  
Go Version   | go1.21.0
Platform     | linux   
Architecture | amd64   
Version         | v2.5.1
Package Manager | apt   
Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 24.0.5                 
gcc        | build-essential       | Installed | 12.9ubuntu3            
libgtk-3   | libgtk-3-dev          | Installed | 3.24.37-1ubuntu1       
libwebkit  | …
```
=> set the background color for window

v2/internal/frontend/desktop/linux/frontend.go, website/src/pages/changelog.mdx
So that apps that have a headless / non-gui mode will be able to run, since they needn't call `NewFrontend` (which is called by `CreateApp`). Previously, `init()` would call `C.gtk_init` regardless of whether CreateApp was called.
Also, we call `C.gtk_init_check` and check the return value (and panic on failure), instead of `C.gtk_init`, since `gtk_init` just exits the process if it fails, without a sensible error message.
Fixes #2628.
Inspired by #2629, but slightly cleaner imho.
Unset `DISPLAY` env var  
Run our app (which has a `--headless` flag) in headless mode, and it runs ok. Before the change, it would exit.
Run the app without the `--headless` flag, and see a stacktrace:
```
panic: failed to init GTK
goroutine 1 [running, locked to …
```
=> Init GTK in `NewFrontend`, not `init`

v2/internal/frontend/desktop/linux/window.go, website/src/pages/changelog.mdx
This PR fixes disable window resize by setting the gtk_window_set_default_size when the window is created.
Fixes #2780
Tested on Ubuntu 23.04 with existing an new projects.
```shell
OS           | Ubuntu  
Version      | 23.04   
ID           | ubuntu  
Go Version   | go1.21.0
Platform     | linux   
Architecture | amd64   
Version         | v2.5.1
Package Manager | apt   
Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 24.0.5                 
gcc        | build-essential       | Installed | 12.9ubuntu3            
libgtk-3   | libgtk-3-dev          | Installed | 3.24.37-1ubuntu1       
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.40.5-0ubuntu0.23.04.1
npm        | …
```
=> fix disable window resize

v2/pkg/commands/build/build.go
use `shlex`, rather than `strings` package, to split pre/post-build command
Yes
Wails CLI v2.5.1
...|...
-------------|--------------
OS           | ArcoLinux
Version      | Unknown  
ID           | arcolinux
Go Version   | go1.20.5 
Platform     | linux    
Architecture | amd64    
Version         | v2.5.1
------------------|---------
Package Manager | pacman
Dependency | Package Name | Status    | Version
-------------------|------------------------|-------------|------------
*docker    | docker       | Installed | 1:24.0.5-1 
gcc        | gcc          | Installed | 13.2.1-3   
libgtk-3   | gtk3         | Installed | 1:3.24.38-1
libwebkit  | webkit2gtk   | Installed | 2.40.5-1   
npm        | npm          | Installed | 9.8.1-1    
pkg-config …
=> [bugfix] build hook command parsing

v3/pkg/application/linux_cgo.go
Currently v3 does not compile under Linux with the following error:
```shell
In file included from _cgo_export.c:4:
linux_cgo.go: In function ‘new_message_dialog’:
linux_cgo.go:89:8: error: format not a string literal and no format arguments [-Werror=format-security]
cc1: some warnings being treated as errors
```
It now compiles  
```shell
nix-shell -I nixpkgs=channel:nixpkgs-unstable -p gcc pkg-config nsis upx gtk3 webkitgtk go_1_21
```
(wails doctor seems to detect wrong Go version)
```console
OS           | NixOS   
Version      | 23.05   
ID           | nixos   
Go Version   | go1.20.7
Platform     | linux   
Architecture | amd64   
Version         | v2.5.1 
Package Manager | nixpkgs
Dependency | Package Name     | Status    | Version         
*docker    | nixos.docker     | Installed …
```
=> fix: use string formatting in gtk_message_dialog_new

website/docs/reference/runtime/window.mdx
Update the new function params in `WindowSetSize`, `WindowSetMinSize`, `WindowSetMaxSize`, `WindowSetPosition`
I try these functions in DevTools and they show params different from the document.
For `WindowSetSize`, `WindowSetMinSize`, `WindowSetMaxSize`  : `size: Size`->`width: number,height: number`
For `WindowSetPosition` : `position: Position`->`position: Position`
=> Fix some params error in some JS references docs

v2/go.mod, v2/go.sum, website/src/pages/changelog.mdx
Add support go.mod Files with new Go version specification.
Fixes #2875
=> [v2, build] Fixed support for Go 1.21 `go.mod` files

website/versioned_docs/version-v2.6.0/gettingstarted/installation.mdx
just change doc to make the installation command easier to copy.
=> docs: make the install command easier to copy

v2/internal/app/app.go, v2/internal/app/app_dev.go, v2/internal/app/app_devtools.go, v2/internal/app/app_devtools_not.go, v2/internal/app/app_production.go, v2/internal/frontend/desktop/darwin/Application.h, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/frontend.go, v2/internal/frontend/desktop/darwin/main.m, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/window.go, v2/internal/frontend/desktop/windows/frontend.go
This removes some confusion regarding the devtools option by renaming some variables and params from `devtools` to `devtoolsEnabled` so it doesn't get confused with the `-devtools` option as `devtoolsEnabled` is `ture` for dev & debug also.
It should not produce any change, testing should be done with :
`wails dev` => devtools is available
`wails build -debug` => devtools is available
`wails build -devtools` => devtools is available
`wails build` => devtools is NOT available
=> [v2] Refactor devtools (better naming to remove confusion)

website/.gitattributes
https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#documentation
=> [Github] Exclude `/website` from language stats

v2/go.mod, v2/go.sum, v2/internal/frontend/desktop/darwin/Application.h, v2/internal/frontend/desktop/darwin/Application.m, v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/window.go, v2/pkg/options/mac/mac.go, v2/pkg/options/mac/preferences.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
This PR allows to set some of the preferences for the Webview on osx, notably `tabFocusesLinks` and `textInteractionEnabled`. By default, `tabFocusesLinks` is disabled, preventing the user to select links with the tab key.  One could use javascript to workaround this issue, but it's very brittle and error prone. Having a way to turn this setting on increase the accessibility of the app.
Fixes #2919 
I've tested the changes locally with a project I'm currently working on by adding a replace statement in my go.mod to point to the version with my changes. I've added a recording:
https://github.com/wailsapp/wails/assets/5574267/8e7072f8-e2fb-470f-8102-99defaf08abe
- during the first app launch, `tabFocusesLinks` is enabled, pressing tab moves the …
=> [v2 mac] Allow to specify webview preferences

v2/internal/frontend/desktop/darwin/WailsContext.h, v2/internal/frontend/desktop/darwin/WailsContext.m, v2/internal/frontend/desktop/darwin/window.go, v2/pkg/options/mac/preferences.go, website/docs/reference/options.mdx, website/src/pages/changelog.mdx
This PR adds the option to enable/disable fullscreen support on Mac. For example, when this option is enabled, it allows the user to display a video in fullscreen mode.
Fixes # 2099
I've created a new wails app that point to my changes. The app only render a video. When the user hover the video a fullscreen button is displayed allowing the user to switch in fullscreen mode.
https://github.com/wailsapp/wails/assets/5574267/eb338fe3-437f-4f9f-9155-14d12145a7ba
Repository: https://github.com/fkhadra/wails-fix-2099
```sh
Version | v2.6.0
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 13.5.2   |
| ID           | 22G91    |
| Go Version   | go1.21.0 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘ …
```
=> [v2 mac] add fullscreen option to preference

website/docs/community/templates.mdx, website/src/pages/changelog.mdx
Add a new htmx-templ community template
=> Add new htmx/templ template

mkdocs-website/docs/changelog.md, v3/pkg/application/application.go
This will fix a dead lock issue. In darwin, when `Application.Quit` called, it will cause the app frozen in main thread. (use Command + Q in example/window can reproduce this issue)
The `Quit` function in `v3/pkgs/application/application.go` holding `windowsLock` and sent a `windowEvent`. The thread process this event also need this lock.
=> [v3] fix deadlock when quit

v2/pkg/assetserver/assetserver.go, v2/pkg/assetserver/body_recorder.go, website/src/pages/changelog.mdx
It will also be injected into all html files returned when requesting a folder path.
Fixes #2047
=> [assetserver] Inject runtime/IPC into all index html files

v2/internal/frontend/desktop/linux/window.go, v2/pkg/options/linux/linux.go
In NewWindow, set options.Linux.WebviewGpuPolicy to WebviewGpuPolicyNever if options.Linux is nil, disabling GPU acceleration by default on linux until the upstream bugs https://bugs.webkit.org/show_bug.cgi?id=228268 and https://bugs.webkit.org/show_bug.cgi?id=261874 are fixed.
```sh
wails dev
wails build
./build/bin/demo-app
```
```
Version         | v2.6.0
Package Manager | pacman
┌──────────────────────────────────────────────────────────────────────────────────┐
| OS           | Manjaro Linux                                                     |
| Version      | Unknown                                                           |
| ID           | manjaro                                                           |
| Go Version   | go1.21.3 …
```
=> linux: workaround for #2977

v2/internal/frontend/desktop/darwin/AppDelegate.h, v2/internal/frontend/desktop/darwin/AppDelegate.m, v2/internal/frontend/desktop/darwin/single_instance.go
Recently Single Instance lock was introduced for all platforms. During application implementation I found two issues with case, when MacOs app is launched as sandbox app.
1. When app is sandboxed `os.TempDir()` return temp directory, which is not accessible by the app. Changed to native method to get temp directory. It returns proper directory in that case.
2. In sandboxed app `userInfo` is not allowed https://developer.apple.com/forums/thread/129437. Fix implemented to pass message via `object` instead
Signed application with …
=> Fix single instance lock for macOS sandbox app

v2/cmd/wails/build.go, website/src/pages/changelog.mdx
There are `obfuscated` and `garbleargs` properties in wails.json. However they are not accepted in build command. This PR fixes this issue
Tested locally with different project settings in `wails.json`
```
Version  | v2.6.0
Revision | c15fb6235c28d310c8c04f95c4373a6ab38f8ad7
Modified | true
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.0     |
| ID           | 23A344   |
| Go Version   | go1.21.3 |
| Platform     | darwin   |
| Architecture | arm64    |
| CPU          | Unknown  |
| GPU          | Unknown  |
| Memory       | Unknown  |
└─────────────────────────┘
```
=> Pass obfuscation settings from wails.json

website/i18n/zh-Hans/docusaurus-plugin-content-docs/current/reference/runtime/window.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.6.0/reference/runtime/window.mdx, website/i18n/zh-Hans/docusaurus-plugin-content-docs/version-v2.7.0/reference/runtime/window.mdx
docs: fix doc typos
Fix doc typos, `WindowSetSize 获取窗口尺寸` => `WindowGetSize 获取窗口尺寸`
=> docs: fix doc typos

mkdocs-website/docs/en/changelog.md, v3/internal/templates/_common/Taskfile.tmpl.yml
In the same vein as https://github.com/wailsapp/wails/pull/3126, this PR adds a `run:linux` entry to the templater.
Locally, I created a Wails 3 project on my Linux desktop and found `wails3 dev` fell over due to it missing so I added it and it successfully spun up a dev server.
I ran `wails3 dev` locally and the task was successfully found, resulting in a dev server booting up
=> (v3/linux): Add Taskfile template entry for `run:linux`

mkdocs-website/docs/en/changelog.md, v3/examples/hide-window/main.go, v3/pkg/application/systemtray.go, v3/pkg/application/systemtray_darwin.go, v3/pkg/application/systemtray_darwin.h, v3/pkg/application/systemtray_darwin.m
While testing the systray features on `v3.0.0-alpha.3`, I noticed that systray OnClick (and OnRightClick etc) did not work when no window was attached on MacOS.
For example, with the `hide-window` example, there is a callback set for the systray `OnClick` that is supposed to show the window, but when clicked, the callback is never called and the menu opens.
I couldn't find an existing issue for this bug.
I tested using the `hide-window` and `systray` examples.
In the `hide-window` example, the systray `OnClick` callback was well triggered. 
In the `systray` example, everything was working as expected.
I built every examples using `task test:examples`
I ran every tests using `go test -v ./...` 
```
% wails3 doctor
Wails Doctor
Wails CLI    | …
```
=> [V3/macos] Fix systray click handling when no attached window

mkdocs-website/docs/en/changelog.md, v3/pkg/application/dialogs_windows.go
Fixes Windows build failing due to undefined `options`
I tested by compiling `dialogs` example for windows with:
```
GOOS=windows go build ./main.go
```
```
% wails3 doctor
Wails Doctor
Wails CLI    | v3.0.0-alpha.3
Go Version   | go1.21.5
-buildmode   | exe
-compiler    | gc
CGO_CFLAGS   |
CGO_CPPFLAGS |
CGO_CXXFLAGS |
CGO_ENABLED  | 1
CGO_LDFLAGS  |
GOARCH       | arm64
GOOS         | darwin
Name            | MacOS
Version         | 14.2.1
ID              | 23C71
Branding        | Sonoma
Platform        | darwin
Architecture    | arm64
Apple Silicon   | true
CPU             | Apple M1 Pro
Xcode cli tools | 2405
CPU             | Unknown
GPU             | Unknown
Memory          | Unknown
SUCCESS  Your system is ready for Wails development! …
```
=> [v3/Windows] Fix failing Windows build due to undefined options

mkdocs-website/docs/en/API/fullapi.md, mkdocs-website/docs/en/changelog.md, v3/examples/show-macos-toolbar/README.md, v3/examples/show-macos-toolbar/main.go, v3/go.mod, v3/pkg/application/options_mac.go, v3/pkg/application/webview_window_darwin.go, v3/pkg/application/webview_window_darwin.h, v3/pkg/application/webview_window_darwin.m
When the MacTitleBar.UseToolbar option is enabled, the system toolbar is shown on macOS windows. Currently, when the windows are switched to fullscreen mode, the toolbar remains visible.
Although this might be desirable sometimes, in most common cases it is not the expected behaviour, as the full-screen toolbar cannot be made transparent and therefore clashes with the look of the application.
This patch introduces a new option in the `MacTitleBar` struct that when enabled hides the toolbar automatically upon entering fullscreen mode. It also enables the option by default in the predefined titlebar styles.
The new [`hide-macos-toolbar` example](https://github.com/fbbdev/wails/tree/feature/hide_fullscreen_toolbar/v3/examples/hide-macos-toolbar) creates two windows shocasing the two possible …
=> [v3] Add option for showing the toolbar in fullscreen mode on macOS

mkdocs-website/docs/en/changelog.md, v3/internal/assetserver/assetserver.go
Correctly compute `startURL` across multiple `GetStartURL` invocations when `FRONTEND_DEVSERVER_URL` is present.
Fixes [#3298](https://github.com/wailsapp/wails/issues/3298)
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | 4467a1ffa273059da10b45bbfd38c656f9e6dc28
Modified       | true
-buildmode     | exe
-compiler      | gc
CGO_CFLAGS     |
CGO_CPPFLAGS   |
CGO_CXXFLAGS   |
CGO_ENABLED    | 1
CGO_LDFLAGS    |
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1 …
=> Correctly compute 'startURL' when using a frontend development server.

v3/internal/commands/appimage.go
Locating the files to bundle webkit into an appimage was hard coded to `/usr/lib` which is not the case everytime.
Fixed to search `/usr/` directory entirely as well as report back which necessary files are missing 
Mentioned in Discord
- [X ] Bug fix (non-breaking change which fixes an issue)
```
Wails CLI      | v3.0.0-alpha.3
Go Version     | go1.22.0
Revision       | f38532bcf5be446ebbf2b68498bb4521975b10fc
Modified       | true
-buildmode     | exe
-compiler      | gc
CGO_CFLAGS     |
CGO_CPPFLAGS   |
CGO_CXXFLAGS   |
CGO_ENABLED    | 1
CGO_LDFLAGS    |
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1
GOARCH         | amd64
GOOS           | linux
vcs …
```
=> Fix appimage file sourcing

v3/pkg/application/dialogs.go, v3/pkg/application/dialogs_linux.go, v3/pkg/application/linux_cgo.go
(New PR due to unfortunate git circumstances)
Linux file chooser dialogs were having varying errors due to not being called on the main gtk thread. The only change was removing the call to create the dialog from the go routine to handle the response so only the handling of the dialog is done outside of the main thread but the chooser is called correctly.
Marked as draft because there is still an issue of selecting a directory it only ever goes into the directory and not selects.
Fixes #3378 
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Linux
```
Wails CLI    | v3.0.0-alpha.4
Go Version   | go1.22.0
Revision     | c1ab0a91fdac1257c74244e45dbcb094d2ad4388
Modified     | true
-buildmode   | exe
-compiler    | gc
CGO_CFLAGS   |
CGO_CPPFLAGS |
CGO_CXXFLAGS |
CGO_ENABLED …
```
=> [V3 Linux]  Calling dialogs on main thread

v3/pkg/application/application_linux.go, v3/pkg/application/linux_cgo.go, v3/pkg/application/webview_window_linux.go
This PR loads and displays `application.Options.Icon` on linux.
I have embedded a custom icon in a test project.
```shell
Wails CLI    | v3.0.0-alpha.4
Go Version   | go1.22.0                                
Revision     | 238b9ede787b693705fc0a9a8f36da50ac44f6b2
Modified     | true                                    
-buildmode   | exe                                     
-compiler    | gc                                      
CGO_CFLAGS   |                                         
CGO_CPPFLAGS |                                         
CGO_CXXFLAGS |                                         
CGO_ENABLED  | 1                                       
CGO_LDFLAGS  |                                         
GOAMD64      | v1                                      
GOARCH       | amd64 …
```
=> [v3 alpha] implement `setIcon` on linux

v2/internal/s/s.go, website/src/pages/changelog.mdx
=> fix: close copy dst file

v3/pkg/application/application.go, v3/pkg/application/events.go
- adds a RegisterListener function on the App struct such that code can listen for WailsEvent(s) even if it isn't a Window
An assumption is made such that Window(s) are implicit listeners and therefore they also are always delivered all WailsEvent(s).
The intent here is to allow for non-Window listeners to be able to register for these events without being a Window itself opening up the ability of plugins or other code that wishes to receive **ALL** `WailsEvent(s)` such that they can be processed.
=> allow for non-Window WailsEvent listeners

v3/internal/commands/build_assets/devmode.config.tmpl.toml, website/src/pages/changelog.mdx
Current dev mode config calls the executable by its path, this changes the dev mode config to use `wails3 task run` to match whatever OS you are on
Issue mentioned in discord
- [ X ] Bug fix (non-breaking change which fixes an issue)
```
| Name         | Ubuntu                             |
| Version      | 22.04                              |
| ID           | ubuntu                             |
| Branding     | 22.04.3 LTS (Jammy Jellyfish)      |
| Platform     | linux                              |
| Architecture | amd64                              |
| CPU          | AMD Ryzen 7 3700X 8-Core Processor |
| GPU 1        | Unknown                            |
| Memory       | 12GB                               |
| Wails CLI      | v3.0.0-alpha.4 …
```
=> [V3] Changes dev mode to match OS executable

mkdocs-website/docs/en/changelog.md, v3/internal/templates/_common/Taskfile.tmpl.yml
Running `wails3 run dev` on Mac with a freshly initialised project does not run. Errors with:
```
task: Failed to run task "run": task: Task "run:darwin" does not exist
```
```
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 14.4.1       |
| ID            | 23E224       |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M2 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| …
```
=> update Taskfile.tmpl.yml to include darwin run task

v2/internal/binding/binding_test/binding_anonymous_sub_struct_multi_level_test.go, v2/internal/binding/binding_test/binding_anonymous_sub_struct_test.go, v2/internal/binding/binding_test/binding_emptystruct_test.go, v2/internal/binding/binding_test/binding_importedmap_test.go, v2/internal/binding/binding_test/binding_importedslice_test.go, v2/internal/binding/binding_test/binding_importedstruct_test.go, v2/internal/binding/binding_test/binding_nestedfield_test.go, v2/internal/binding/binding_test/binding_tsgeneration_test.go, v2/internal/typescriptify/typescriptify.go, website/docs/howdoesitwork.mdx, website/src/pages/changelog.mdx
Modifies the `convertValues` TypeScript function defined in `v2/internal/typescriptify/typescriptify.go` to check for both .slice() and .map() functions on an array-like variable, fixing an issue where strings were improperly identified as arrays if the field type was any.
Also updates the relevant tests in `v2/internal/binding/binding_test` to reflect this change.
Fixes #3432
I ran the binding generation tests in `v2/internal/binding/binding_test`, as well as attempted to reproduce issue #3432 which ran as expected.
```
Version | v2.8.1 …
```
=> Fixed issue where createFrom would misidentify strings as arrays

v2/internal/staticanalysis/staticanalysis.go, v2/internal/staticanalysis/staticanalysis_test.go, v2/internal/staticanalysis/test/standard/main.go, v2/pkg/commands/build/build.go, website/src/pages/changelog.mdx
This PR fixes an issue where valid go:embed directives containing patterns instead of relative paths would result in illegal directories being created. The issue lies in `v2/internal/staticanalysis/staticanalysis.go`, where wails iterates through go:embed comments independently of the compiler. This list of embedded paths are read by `CreateEmbedDirectories` in `v2/pkg/commands/build/build.go` to create embedded directories if they don't exist.
I modified staticanalysis.go's `GetEmbedDetailsForFile` to check for the pattern matching characters used by filepath, excluding the escape character which may flag valid windows paths by accident. These paths are ignored. I also added a check in `CreateEmbedDirectories` to make sure the directory being created has no extension. 
I also added an …
=> Fixed an issue where go:embed directives would generate illegal directories

mkdocs-website/docs/en/changelog.md, v3/pkg/application/bindings.go, v3/pkg/application/bindings_test.go, v3/pkg/application/messageprocessor_call.go
As discussed with @leaanthony, this new PR splits off from #3347, which has been closed, all runtime side commits. These are independent of the binding generator and should already benefit users of the current version.
This new PR contains the following fixes (again, runtime only):
- Unmarshal bound method parameters to the correct type.
- Support for multiple error/non-error return values (previously at most 1 non-error and 1 error were supported).
- New test cases for `BoundMethod.Call` by @abichinger.
The binding example and @abichinger's runtime tests run correctly.
```
Go Version     | go1.22.0                                                                      
Revision       | 12d12a33dec1d31f487b70f87bc31e80252f327c …
```
=> [v3] Binding runtime fixes

mkdocs-website/docs/en/changelog.md, v3/internal/doctor/doctor_common.go
The doctor command reports `# Diagnosis WARNING  There are some items above that need addressing!` if npm is **not found** with the system package manager, but **is found** to be available on the path with `exec.Command`.
Not only is there the warning, but there is nothing in the doctor output to indicate what the problem is. That's because there isn't really a problem, it's just that the fact that npm has been found is not propagated back to the caller of `checkCommonDependencies`.
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Fedora Linux                                                                                      |
| Version      | 39 …
```
=> [v3] Correct detection of npm with acceptable version

website/docs/community/templates.mdx
This PR just adds the [wails-lit-shoelace-esbuild-template](https://github.com/Braincompiler/wails-lit-shoelace-esbuild-template) template to the community templates page.
=> Add "wails-lit-shoelace-esbuild-template" to community templates page

.github/workflows/pr.yml, v2/internal/frontend/desktop/linux/clipboard.go, v2/internal/frontend/desktop/linux/frontend.go, v2/internal/frontend/desktop/linux/gtk.go, v2/internal/frontend/desktop/linux/keys.go, v2/internal/frontend/desktop/linux/menu.go, v2/internal/frontend/desktop/linux/screen.go, v2/internal/frontend/desktop/linux/webkit2.go, v2/internal/frontend/desktop/linux/window.go, v2/pkg/assetserver/webview/request_linux.go, v2/pkg/assetserver/webview/responsewriter_linux.go, v2/pkg/assetserver/webview/webkit2_36+.go, v2/pkg/assetserver/webview/webkit2_40+.go, v2/pkg/assetserver/webview/webkit2_41.go, v2/pkg/assetserver/webview/webkit2_legacy.go, website/src/pages/changelog.mdx
This pr allows for v2 to build for Ubuntu 24.04 and any other OS releases coming out where `webkit2gtk-4.0` is unavailable by adding the `webkit2_41` tag
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] Linux
```
Version         | v2.8.2
Revision        | 1193fe97997d62ec2a61665628ef072b944ad181
Modified        | true
Package Manager | apt
┌─────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                                                   |
| Version      | 24.04                                                                    |
| ID           | ubuntu                                                                   |
| Go Version   | go1.22.2 …
```
=> allow builds for webkit2gtk-4.1

.github/workflows/build-and-test.yml, website/src/pages/changelog.mdx
Fix pipeline build errors by bumping to Go 1.22
=> Bump Go to 1.22 in pipelines

v2/pkg/assetserver/assethandler_external.go
This PR alters how the `NewProxyServer` method is implemented under the hood. It should still function as normal. This was done to revert the way default middleware would work on non-mac platforms.
=> Use NewSingleHostReverseProxy

v2/internal/frontend/desktop/darwin/WailsContext.m, website/src/pages/changelog.mdx
There is an inconsistency of window position values on MacOS. When getting the window position using `runtime.WindowGetPosition()` and setting it back using `runtime.WindowSetPosition()` the `y` value decrements. This is caused by using different screen frame sizes while reading and writing window positions.
We are using `[screen frame]` while setting the position and using `[screen visibleFrame]` while reading it.
`frame` property returns the fullscreen rectangle of the screen, while `visibleFrame` returns the area not occupied by dock and menubar.
I have changed `[screen frame]` to `[screen visibleFrame]` in `v2/internal/frontend/desktop/darwin/WailsContext.m` and the issue seems to be fixed on my tests.
Fixes #3478 
Please describe the tests …
=> Fix window position inconsistency in MacOS

v2/internal/binding/binding_test/binding_structwithoutfields_test.go, v2/internal/binding/binding_test/binding_test.go, v2/internal/binding/binding_test/binding_tsgeneration_test.go, v2/internal/typescriptify/typescriptify.go, website/src/pages/changelog.mdx
Addresses #3490 
Fixes #3490
```
Version | v2.8.1
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.4.1                                                                                                                      |
| ID           | 23E224 …
```
=> Bindingings for empty go structs

v3/pkg/application/application_darwin.go, v3/pkg/application/application_linux.go, v3/pkg/application/application_windows.go, v3/pkg/application/menu.go, v3/pkg/application/menu_darwin.go, v3/pkg/application/menu_linux.go, v3/pkg/application/menu_test.go, v3/pkg/application/menu_windows.go, v3/pkg/application/menuitem.go, v3/pkg/application/menuitem_darwin.go, v3/pkg/application/menuitem_dev.go, v3/pkg/application/menuitem_linux.go, v3/pkg/application/menuitem_test.go, v3/pkg/application/menuitem_windows.go, v3/pkg/application/roles.go, v3/pkg/application/webview_window_linux.go
This PR cointains:
- `application.DefaultApplicationMenu() *Menu` which will return the default application menu for the current platform
- `Menu.FindByLabel(label string)` to find a menu item by its label. Returns nil if not found.
- `Menu.ItemAt(index int)` for retrieving menu items by index. Returns nil if out of bounds.
- `Menu.RemoveMenuItem(*MenuItem)` for removing a menu item.
- `MenuItem.RemoveAccelerator()` for removing the accelerator.
- `MenuItem.GetAccelerator() string` for getting a menu item's accelerator.
- `MenuItem.GetSubmenu() *Menu` for getting a submenu (nil if not a submenu item).
`Menu.Update()` needs calling after any changes.
=> Menu improvements

mkdocs-website/docs/en/changelog.md, v3/internal/templates/templates.go
Fixes an issue where if wails is installed in the `C:\` drive attempting to create a project on any other volume would result in an error due to not being able to set the relative path for the project.
This change gets the `filepath.VolumeName()` of each path and compares if they are different and hardcodes the full path if they differ
Raised by discord memeber.
- [ X ] Bug fix (non-breaking change which fixes an issue)
```
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
| Name              | Windows 10 Home                                                              |
| Version           | 2009 (Build: 22631)                                                          |
| ID …
```
=> [V3] fix windows cross volume project init

mkdocs-website/docs/en/changelog.md, v3/pkg/application/application_linux.go
This change addresses an issue encountered on NixOS where the data passed in from the `Body` element contains data other than an `[]interface{} of string values`.  
Updating the code to do a safe type assertion instead of blindly asserting it is a string.   
This seems to resolve the crash but further investigation should be done to see what other types of values might be included in the `dbus.Signal.Body` field.
=> linux: theme handling bugfix

mkdocs-website/docs/en/learn/guides/customising-windows.md, mkdocs-website/mkdocs.yml, v3/examples/window/main.go, v3/pkg/application/messageprocessor_window.go, v3/pkg/application/webview_window.go, v3/pkg/application/webview_window_darwin.go, v3/pkg/application/webview_window_linux.go, v3/pkg/application/webview_window_options.go, v3/pkg/application/webview_window_windows.go, v3/pkg/application/window.go, v3/pkg/w32/window.go, v3/wep/proposals/titlebar-buttons/proposal.md
**Author**: Lea Anthony
**Created**: 2024-05-20
This is a proposal for an API to control the appearance and functionality of window controls in Wails.
This will only be available on Windows and macOS.
We currently do not fully support the ability to customise window controls. 
1. A new enum will be added:
```go
type ButtonState int
const (
ButtonEnabled  ButtonState = 0
ButtonDisabled ButtonState = 1
ButtonHidden   ButtonState = 2
)
```
2. These options will be added to the `WebviewWindowOptions` option struct:
```go
MinimiseButtonState ButtonState
MaximiseButtonState ButtonState
CloseButtonState    ButtonState
```
3. These options will be removed from the current Windows/Mac options:
- DisableMinimiseButton
- DisableMaximiseButton
- DisableCloseButton
4. These methods will be added to …
=> [WEP] Customise Window Titlebars

website/docs/guides/windows.mdx, website/src/pages/changelog.mdx, website/versioned_docs/version-v2.8.1/guides/windows.mdx
Specify to the user that the WebView Runtime dependency must be extracted before being used.
> [!NOTE]
> I am not an English speaker, so I apologize in advance for any language-related mistakes I may have made.
_Fixes incomplete documentation._
Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as …
=> Documentation: Specify how to handle the Fixed WebView Runtime.

v3/internal/go-common-file-dialog/cfd/DialogConfig.go
Windows crashes when setting a file dialog directory to one that does not exist
Adds os.Stat errors before creating the dialog 
```
┌──────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Ubuntu                                                                    |
| Version      | 24.04                                                                     |
| ID           | ubuntu                                                                    |
| Branding     | 24.04 LTS (Noble Numbat)                                                  |
| Platform     | linux                                                                     |
| Architecture | amd64                                                                     |
| CPU          | …
```
=> [V3/Windows] Fix Windows Dialog crash on invalid folder path

mkdocs-website/docs/en/changelog.md, v3/pkg/application/webview_window.go
A recent change to the messaging system broke the `wails:resize:<border>` message due to adding `wails:` prefix, this fix corrects the length check and parameter used in the resize function.
Also fixes a slog key error
- [X ] Linux
```
┌──────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Ubuntu                                                                    |
| Version      | 24.04                                                                     |
| ID           | ubuntu                                                                    |
| Branding     | 24.04 LTS (Noble Numbat)                                                  |
| Platform     | linux                                                                     |
| …
```
=> fix resize messaging

v3/internal/runtime/desktop/@wailsio/runtime/package.json, v3/pkg/application/linux_cgo.go
Fix HTML renderer on Linux resize
- [ X ] New feature (non-breaking change which adds functionality)
- [X ] Linux
```
┌──────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Ubuntu                                                                    |
| Version      | 24.04                                                                     |
| ID           | ubuntu                                                                    |
| Branding     | 24.04 LTS (Noble Numbat)                                                  |
| Platform     | linux                                                                     |
| Architecture | amd64                                                                     |
| CPU          | 12th Gen …
```
=> [V3-Linux] fix resize and update @wailsio runtime

v3/pkg/application/application.go, v3/pkg/application/application_darwin.go, v3/pkg/application/application_linux.go, v3/pkg/application/application_windows.go
Recent changes to application.go broke non-windows builds by calling w32 directly. This PR adds a `fatalHandler(errFunc func(error))` to stub out the process for non-windows builds and keep the `w32.Fatal` setting only in a `application_windows.go`
```
Wails Doctor
┌──────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Ubuntu                                                                    |
| Version      | 24.04                                                                     |
| ID           | ubuntu                                                                    |
| Branding     | 24.04 LTS (Noble Numbat)                                                  |
| Platform     | linux …
```
=> Add fatalHandler() stubs to fix non-windows builds

v2/pkg/templates/generate/assets/vue-ts/frontend/READ-THIS.md, v2/pkg/templates/templates/vue-ts/frontend/READ-THIS.md
Issue was fixed via #1813 and the extra readmes is not needed anymore
Removed `v2/pkg/templates/templates/vue-ts/frontend/READ-THIS.md` & `v2/pkg/templates/generate/assets/vue-ts/frontend/READ-THIS.md`.
```bash
Version         | v2.9.1
Package Manager | apt   
┌───────────────────────────────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                                             |
| Version      | 22.04                                                              |
| ID           | ubuntu                                                             |
| Go Version   | go1.23.0                                                           |
| Platform     | linux …
```
=> Removed unnecessary files. Fixes #3737

mkdocs-website/docs/en/changelog.md, v3/examples/window/main.go, v3/pkg/application/webview_window.go, v3/pkg/application/webview_window_darwin.go, v3/pkg/application/webview_window_linux.go, v3/pkg/application/webview_window_options.go, v3/pkg/application/webview_window_windows.go
This change adds a new `InitialPosition` option to `WebviewWindowOptions` to determine where the window should be initially positioned. Valid options are: 
- `WindowCentered` - Center on start
- `WindowXY` - Place the window at the position specified by the `X` and `Y` option values
=> V3 alpha feature/start window position

mkdocs-website/docs/en/changelog.md, mkdocs-website/docs/en/learn/bindings.md, v3/pkg/application/messageprocessor_call.go
When a bound call uses `context.Context` the calling window (if called from the frontend) ID and Name can be retrieved using context keys:
```go
func (s *MyService) WindowAwareMethod(ctx context.Context) (string, error) {
windowName := ctx.Value(application.WindowNameKey).(string)
windowID := ctx.Value(application.WindowIDKey).(string)
return fmt.Sprintf("Called from window: %s (ID: %s)", windowName, windowID), nil
}
```
Also addresses an unchecked error.
=> V3 alpha - calling window id and name

docs/src/content/docs/changelog.mdx, v3/internal/assetserver/asset_fileserver.go
sveltekit by default creates routes by creating `[route].html` files in the fs root, however wails3 assetFileServer will fail on requests with no extension if a file with no extension doesn't exist. This causes multi page apps to only show the main route (`index.html`), so I added to the assetFileServer a check if `filename` doesn't exist to see if `[filename].html` exists.
Please select the option that is relevant.
*edit: forgot to add this part*
set up a new project with sveltekit template. added a second route and a button to call a func to open a new window with said route. Before my change the new window would open with a "not found" from webview, after the change the correct page opens. I also manually edited the `frontend/dist` to remove the `.html` extension and the pages still …
=> [V3] add ".html" to assetFileServer requests with no extension
